### ISSUE TITLE
ipv6 cidr

### ISSUE THREAD

**Issue by FernandoMiguel** [terraform-aws-modules/terraform-aws-security-group#10]
the correct cidr for wide open IPv6 is ::/0 not 0.0.0.0/0

**Comment by antonbabenko** [comment]
Yes, there are two different variable which this module accepts. One for IPv4 and another for IPv6 CIDR blocks, for example:

```
ingress_cidr_blocks = ["10.10.0.0/16"]
ingress_ipv6_cidr_blocks = ["2001:db8::/64"]
```
