### ISSUE TITLE
Why use comma separated string for cidr_blocks instead of list in ingress_icmp_with_cidr_blocks

### ISSUE THREAD

**Issue by powellquiring** [terraform-aws-modules/terraform-aws-security-group#105]
snip:
```
module "using_terraform-aws-security-group" {
 ingress_with_cidr_blocks = [
    {
      rule        = "postgresql-tcp"
      cidr_blocks = "0.0.0.0/0,2.2.2.2/32"
    },
```

Why is cidr_blocks a comma separated string instead of a list, like this?
```
module "using_terraform-aws-security-group" {
 ingress_with_cidr_blocks = [
    {
      rule        = "postgresql-tcp"
      cidr_blocks = ["0.0.0.0/0", "2.2.2.2/32"]
    },
```

**Comment by powellquiring** [comment]
Thanks for the great module!!!

**Comment by antonbabenko** [comment]
You are welcome! If I remember correctly the reason for this was that it is not possible to use a list inside map which is inside a list... This is one of the limitations of the current version of Terraform. Maybe it will be improved in the upcoming versions of Terraform.
