### ISSUE TITLE
The README, Inputs section is not really readable

### ISSUE THREAD

**Issue by thomsh** [terraform-aws-modules/terraform-aws-security-group#106]
Hello,
The README, Inputs section is not really readable.
Any way to improve this ?

**Comment by antonbabenko** [comment]
I agree that it is hard to use in the way it is written now. Since this documentation is generated automatically from source code I don't know how we can easily change this. If you have ideas, please share.

Normally, users find all necessary arguments and working examples in `examples` folder.

**Comment by thomsh** [comment]
Ok, thanks for your answer, 
unfortunately the only idea I have: put inputs named `auto_groups` & `rules` in another file dot `.md` as an exception for this two, and that sound not so good.

**Comment by antonbabenko** [comment]
It is unlikely that I am going to work on improving this autogenerated documentation and generate it differently from all other repositories.

Please check `examples` and maybe we can improve them to show other use-cases as the code.

Closing this issue.
