### ISSUE TITLE
Rule rabbitmq-15672-tcp defines wrong(?) port

### ISSUE THREAD

**Issue by brnl** [terraform-aws-modules/terraform-aws-security-group#107]
The rule 'rabbitmq-15672-tcp' is named but defines port '15671' instead of the expected port 15672. Is this by design?

https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/9a0e3483f671a691dbe26609d3b92a81fc846a50/rules.tf#L110

**Comment by antonbabenko** [comment]
This is a bug. Should it be 15672?

**Comment by brnl** [comment]
Yes, 15671 doesn't seem to be used by default. https://www.rabbitmq.com/networking.html#ports

**Comment by antonbabenko** [comment]
[v2.15.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/v2.15.0) has been released.

Thanks @brnl !
