### ISSUE TITLE
Add custom ports to ingress rules

### ISSUE THREAD

**Issue by xabim** [terraform-aws-modules/terraform-aws-security-group#108]
Hi, I have a new port to add for a service in ingress rules, as example:

```
module "custom_service_sg" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "2.15.0"

  name        = "service-not-in-rules-sg"
  description = "Security group with custom port open"
  vpc_id      = "${data.aws_vpc.default.id}"

  ingress_with_cidr_blocks =[
    {
    from_port = 4567
    to_port   = 4567
    protocol  = "tcp"    
    cidr_blocks = "${var.office_ip}"
    },
  ]
}
```

If I have like 20 offices ip to open the same port is there any way to achieve this instead of create 20 times the same rule?

I was thinking about a PR to get the new service port in the module or a way to use **ingress_rules** with custom ports like for example:

```
ingress_custom_rules = [
  {
    from_port = 4567
    to_port = 4567
    protocol = "tcp"
  },
]
```

**Comment by antonbabenko** [comment]
This kind of features may look nice, but it will increase the complexity of the module even more.

I think the easiest way can be to produce a list of maps using interpolation functions Terraform provide and pass such list to this module.

There is nothing we can do in this module, closing this issue.
