### ISSUE TITLE
VPC ID in computed_ingress_cidr_blocks?

### ISSUE THREAD

**Issue by cabrinha** [terraform-aws-modules/terraform-aws-security-group#112]
Example in README shows VPC ID being passed into `computed_ingress_cidr_blocks` list.

Is this module supposed to allow VPC IDs to be passed into that parameter?

```terraform
module "db_computed_sg" {
  # omitted for brevity

  ingress_cidr_blocks = ["10.10.0.0/16", "${data.aws_security_group.default.id}"]

  computed_ingress_cidr_blocks = ["${module.vpc.vpc_id}"]
  number_of_computed_ingress_cidr_blocks = 1
}

module "db_computed_merged_sg" {
  # omitted for brevity

  computed_ingress_cidr_blocks = ["10.10.0.0/16", "${data.aws_security_group.default.id}", "${module.vpc.vpc_id}"]
  number_of_computed_ingress_cidr_blocks = 3
}
```

If the module does not allow VPC IDs to be passed in, please update the README.

**Comment by fabiendelpierre** [comment]
That has to be a typo, because it makes no sense to use the `vpc_id` output in this case and would never work. They mean the `vpc_cidr_block` output of the vpc module.

**Comment by antonbabenko** [comment]
Thanks for paying attention to README and details!

[v3.0.1](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/v3.0.1) has been released.
