### ISSUE TITLE
Predictable output attributes

### ISSUE THREAD

**Issue by shmick** [terraform-aws-modules/terraform-aws-security-group#114]
Typically one would expect the output of a resource or a module to have predictable attributes, such as `module.name.id` or `module.name.vpc_id`

Would you consider adding these outputs to the module. You could keep the existing `this_security_group_*` outputs and add the more common ones in order to keep backwards compatiability with those already using things like `module.name.this_security_group_id`

**Comment by antonbabenko** [comment]
I have described the rules for naming outputs here - https://www.terraform-best-practices.com/naming#outputs 

tldr; There can be multiple resources with the same attributes (eg, `name` or `id`), so outputs will be hard to identify.
