### ISSUE TITLE
3.0 Version doesn't pass parsing

### ISSUE THREAD

**Issue by POD666** [terraform-aws-modules/terraform-aws-security-group#121]
Looks like newly released 3.0 doesn't pass parsing:
```
$ terraform init
Initializing modules...
...
...
- module.environment.rds.db_computed_source_sg
  Found version 3.0.0 of terraform-aws-modules/security-group/aws on registry.terraform.io
  Getting source "terraform-aws-modules/security-group/aws"
Error downloading modules: Error loading modules: module db_computed_source_sg: Error parsing .terraform/modules/17f749b05082bf21043a5113f0f19869/terraform-aws-modules-terraform-aws-security-group-f87a81c/main.tf: At 5:16: Unknown token: 5:16 IDENT concat
ERROR: Job failed: command terminated with exit code 1
```

Link to [main.tf](https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/main.tf#L5).

**Comment by VitaliiH** [comment]
Hi @POD666 
Had the same issue. My terraform version is 0.11.11. Do you have the same?

I provided version = "2.17.0" in each security group and it worked.

**Comment by brnl** [comment]
Same here. This is my tf:

`module "sg_bastion" {
  source      = "terraform-aws-modules/security-group/aws"

  version     = "~> 2.17"
  
  name        = "sg_${var.project_name}-bastion"
  description = "Security group for bastion servers"
  vpc_id      = "${aws_vpc.brnl-test1-main.id}"

  tags        = "${local.common_tags}"
  
  ingress_with_cidr_blocks = [
    {
      rule        = "ssh-tcp"
      description = "SSH from definded management IPs"
      cidr_blocks = "${join(",", var.management_ips)}"
    }
  ]

  egress_with_cidr_blocks = [
    {
      rule        = "all-tcp"
      cidr_blocks = "0.0.0.0/0"
    },
  ]
}
`

**Comment by antonbabenko** [comment]
Use version `~> 3.0` for Terraform 0.12, and `~> 2.0` for Terraform 0.11.

@brnl double check that you have `version = "~> 2.17"` and remove `#` from that line.

Also, remember to remove cached folder `.terraform`.

**Comment by brnl** [comment]
@antonbabenko do you mean 3.0 is not (and will not be) 0.11 compatible at all by design? Is it not possible to generate a descriptive warning/error for that?

_And I commented the version pinning out just for this post ;-)_

**Comment by antonbabenko** [comment]
That is right, 3.0+ is for Terraform 0.12 only because there is new syntax. `3.0` **does not** introduce new features comparing to `2.17.0` which is the latest which runs on Terraform 0.11.

**Comment by POD666** [comment]
Well, I agree with @brnl, there should be some descriptive warning/error.
But overall this issue might be closed as we already have 2 solutions:

- upgrade Terraform to 0.12
- specify `version = "~> 2.17"`

**Comment by sethfloydjr** [comment]
Yep...could have a more descriptive error.

**Comment by antonbabenko** [comment]
Yeah, but we can't do anything regarding the ways how Terraform shows the errors.
