### ISSUE TITLE
Error on terraform v0.1.14

### ISSUE THREAD

**Issue by normed** [terraform-aws-modules/terraform-aws-security-group#126]
Hi .
I was successfully using your modules with Terragrunt v0.18.6 and terraform v0.11.14
today i tried a plan  and i had the following issue 
module "sgr_external_alb" {
  source = "github.com/terraform-aws-modules/terraform-aws-security-group.git"
 Error downloading modules: Error loading modules: module sgr_external_alb: Error parsing .terraform/modules/70929e54b500d00c006b672897ba0996/main.tf: At 5:16: Unknown token: 5:16 IDENT concat
I removed the cache, tried a terrform init . i have the same issue
Regards

**Comment by antonbabenko** [comment]
For Terraform 0.11, you should specify the version of the module to be `v2.*` (for example, `v2.17.0`).

If you are using terragrunt, you can do like this:
```
source = "github.com/terraform-aws-modules/terraform-aws-security-group.git?ref=v2.17.0"
```

**Comment by normed** [comment]
it works
Thanks.
