### ISSUE TITLE
Pinned version of /modules/https-443 2.0 not found

### ISSUE THREAD

**Issue by jeffsteinmetz** [terraform-aws-modules/terraform-aws-security-group#127]
The 2.x pinned version of `/modules/https-443` is not found,
using

```
  source                       = "terraform-aws-modules/security-group/aws//modules/https-443"
  version                      = "~> 2.0"
```

returns

```
Error downloading modules: Error loading modules: module my_alb_sg: No Terraform configuration files found in directory: .terraform/modules/005e02a628a4a8cfacbd55b9aa4934c7
```

bumping to `"~> 3.0"` does work, however we are still on terraform 0.11.4 so we need to resolve the pre 3.0 version correctly.

also tried `"v2.17.0"` and other various 2.x versions with same error result.

**Comment by antonbabenko** [comment]
Strange, it is working as expected for me. Try to remove `.terraform` directory and run `terraform init` once more.

**Comment by jeffsteinmetz** [comment]
confirmed, works again.  will close.  maybe it was a temporary network issue.
