### ISSUE TITLE
terraform plan removing existing security group resource

### ISSUE THREAD

**Issue by RanjitRajput** [terraform-aws-modules/terraform-aws-security-group#129]
using this module I have created security group as below.
$ terraform state list
module.security_sg.aws_security_group.this
module.security_sg.aws_security_group_rule.ingress_with_cidr_blocks

Now, when I am trying to create the new security group, it's trying to destroy existing resource and create new one.
Plan output as below :

-/+ module.security_sg.aws_security_group.this (new resource required)

-/+ module.security_sg.aws_security_group_rule.ingress_with_cidr_blocks[0] (new resource required)

My main.tf file is as below -

provider "aws" {
  region = "${var.region}"
}

module "security_sg" {
  source      = "./../../terraform-aws-security-group/"
  name        = "it-test"
  description = "Test"
  vpc_id      = "vpc-0f21e154a8dce7564"
  use_name_prefix = false

  ingress_with_cidr_blocks = [
    {
      from_port   = 0
      to_port     = 65535
      protocol    = "tcp"
      cidr_blocks = "0.0.0.0/0"
      description = "Managed by Terraform"
    },
    {
      from_port   = 53
      to_port     = 53
      protocol    = "udp"
      cidr_blocks = "0.0.0.0/0"
      description = "Managed by Terraform"
    },
    {
      from_port   = 0
      to_port     = 65535
      protocol    = "udp"
      cidr_blocks = "0.0.0.0/0"
      description = "Managed by Terraform"
    },
  ]

  egress_with_cidr_blocks = [
    {
      from_port   = 0
      to_port     = 0
      protocol    = "-1"
      cidr_blocks = "0.0.0.0/0"
    },
    {
      from_port   = 443
      to_port     = 443
      protocol    = "tcp"
      cidr_blocks = "0.0.0.0/0"
    },
  ]

  tags {
    "Name" = "it-test"
  }

How i can create the new security group resource without affecting the previous one.

**Comment by bryantbiggs** [comment]
the output in your terraform plan will identify why the resource creation is triggered
