### ISSUE TITLE
HTTP 500 when attempting to download the module source

### ISSUE THREAD

**Issue by paulpog-arachnys** [terraform-aws-modules/terraform-aws-security-group#134]
$ terraform init
Initializing modules...
- module.elasticsearch
  Getting source "../../module/elasticsearch"
- module.examplecorp-s3
  Getting source "../../module/s3"
- module.examplecorp-sqs
  Getting source "../../module/sqs"
- module.elasticsearch.es_computed_source_sg
  Found version 2.17.0 of terraform-aws-modules/security-group/aws on registry.terraform.io
  Getting source "terraform-aws-modules/security-group/aws"
Error downloading modules: Error loading modules: bad response code: 500
ERROR: Job failed: command terminated with exit code 1

**Comment by antonbabenko** [comment]
This was most likely a temporary issue on the Terraform Registry side, and there is nothing we should do in the module.

Closing this issue.
