### ISSUE TITLE
16 is CHAOS

### ISSUE THREAD

**Issue by tdewitt** [terraform-aws-modules/terraform-aws-security-group#137]
https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/b1bee72217eaff1e37341d1a4c15abf375c73503/rules.tf#L6

Fun fact: 16 is CHAOS.  _17_ is UDP

**Comment by antonbabenko** [comment]
Pretty good catch! I've just fixed it.

The reason why nobody noticed before is that AWS supports specifying common protocols by name.
