### ISSUE TITLE
Required ipv6 when using ingress_with_cidr_blocks?

### ISSUE THREAD

**Issue by anthonydeaver** [terraform-aws-modules/terraform-aws-security-group#14]
Not sure if this is the proper place or not, but...
using this bit of code: 

    module "internal_sg" {
        source = "github.com/terraform-aws-modules/terraform-aws-security-group?ref=v1.1.4"

        name        = "user-service"
        description = "Security group"
        vpc_id      = "${module.vpc.vpc_id}"
        ingress_cidr_blocks      = ["0.0.0.0/0"]
        ingress_rules            = ["http-80-tcp", "https-443-tcp"]

        ingress_with_cidr_blocks = [
            {
                from_port   = 8080
                to_port     = 8090
                protocol    = "tcp"
                description = "User-service ports"
                cidr_blocks = "0.0.0.0/0"
          }
      ]
    }

I consistently get the error: `Error: module.internal_sg.aws_security_group_rule.ingress_with_cidr_blocks: "ipv6_cidr_blocks.0" must contain a valid CIDR, got error parsing: invalid CIDR address:`

I'm not using IPV6, and I'm not including it in the module definition.

Version is terraform 0.10.8.

**Comment by aterreno** [comment]
Yeah I've got the same issue

**Comment by antonbabenko** [comment]
Thanks for reporting this bug and that you provided example code (it always saves my time!).

A new version [v1.2.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/tag/v1.2.0) has been released and it should fix this problem. I have added example into `examples/complete/main.tf` which shows various use-cases.

**Comment by analytically** [comment]
Still seeing this issue.
