### ISSUE TITLE
During destroy rule for SG deletes before resource

### ISSUE THREAD

**Issue by KursLabIgor** [terraform-aws-modules/terraform-aws-security-group#140]
terraform 0.11.
In case if we create SG for RDS and both resources are modules , seems like dependency doesn't work properly and SG rules deletes before RDS resources in result I lost connection RDS and destroy fails.
Maybe possible add additional var for explicitly specify dependency between modules

**Comment by bryantbiggs** [comment]
hi @KursLabIgor see https://discuss.hashicorp.com/t/how-can-i-achieve-dependency-between-modules/4331/2

**Comment by KursLabIgor** [comment]
Ok. close it.
