### ISSUE TITLE
how to pass security_grp_id as ingress

### ISSUE THREAD

**Issue by saikiran243** [terraform-aws-modules/terraform-aws-security-group#146]
can u help me out how can i pass a sg-id as in the ingress block
module "traffic-allow" {
   source = "./sec-grp-modules/modules/https-443"
   name = "sg-name"
   vpc_id = module.app-vpc.vpc_id
   ingress_cidr_blocks = ["sg-0e332fa0cda"]
}

Error occured while planning:
"cidr_blocks.0" must contain a valid CIDR, got error parsing: invalid CIDR address: sg-0e332fa0cda

**Comment by burnsflipper** [comment]
The "cidr_blocks" parameters take cidr blocks as input.

The "source_security_group_id" parameters take a source security group ID as input.

**Comment by rba1-source** [comment]
The "cidr_blocks" parameters take cidr blocks as input.

The "source_security_group_id" parameters take a source security group ID as input.

**Comment by saikiran243** [comment]
@rba1-source thanks for the reply can u guide me on how can i include it in my main.tf 
as my situation here is i want to open a port of my instance to alb security group so i want to pass the value in my main.tf only

**Comment by rba1-source** [comment]
```
resource "aws_security_group_rule" "webserver-lb_website_monitoring" {
  type                     = "ingress"
  from_port                = 443
  to_port                  = 443
  protocol                 = "tcp"
  security_group_id        = "${var.webserver-lb_sg_id}"
  cidr_blocks              = ["10.198.74.17/32"]
}
```
I use this repo as a module to create the security groups without rules (and it outputs module.webserver-lb.this_security_group_id as var.webserver-lb_sg_id), then I use the aws_security_group_rule resources to add as many rules as I need to that security group.

Doing it this way also means you can have security groups which are listed inside other security group rules, without getting the cyclical error (where 2 groups have access to each other, but terraform can't create one group before the other).

**Comment by rba1-source** [comment]
You can find this in the supplied examples.

https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/examples/complete/main.tf
