### ISSUE TITLE
Rules are not being enforced

### ISSUE THREAD

**Issue by lfventura** [terraform-aws-modules/terraform-aws-security-group#149]
1. Create a SG with some rules (Using Terraform with this module)
2. Go to AWS Console and create a new rule
3. Apply the module again

It will not tell that something was manually changed in the SG.

**Comment by hlarsen** [comment]
Just noticed this as well when doing some testing - is this expected?

**Comment by antonbabenko** [comment]
Yes, this is the intended behavior of the module. Terraform does not let us easily manage both cases.

I don't think there is much we can do in the module. At least in the way it is written now.

**Comment by purduemike** [comment]
Isn't one of the core tenants of IaC the ability to ensure infra state. Might just be better to use the aws_security_group resource rather than this module.
