### ISSUE TITLE
Failing to download module

### ISSUE THREAD

**Issue by brucedvgw** [terraform-aws-modules/terraform-aws-security-group#151]
Hey Anton,

As of today I am not hitting an issue with this module where it is failing to download with the below error:
```
Error: Failed to download module

Could not download module "security_group"
(.terraform/modules/rds/main.tf:270) source code from
"https://api.github.com/repos/terraform-aws-modules/terraform-aws-security-group/tarball/v3.2.0//*?archive=tar.gz":
Error opening a gzip reader for
/var/folders/g7/mmk1f7wx2hn3c6yq91b37sfh0000gn/T/getter874260988/archive: EOF.
```

I see that you have pushed a new release `3.3.0` however I get the same error locally and on Terraform Cloud.

**Comment by brucedvgw** [comment]
To get around this issue I have had to copy the module I used locally the previous day.

**Comment by antonbabenko** [comment]
Hi there!

Please check this out -https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/380#issuecomment-572746090

**Comment by antonbabenko** [comment]
The problem is with Terraform and not with the module of a specific version.

**Comment by brucedvgw** [comment]
Got it! Updated the version and works like a charm. Thanks Anton.

**Comment by bryantbiggs** [comment]
I think we can close @antonbabenko
