### ISSUE TITLE
Create rule on an existing group

### ISSUE THREAD

**Issue by pfilbin90** [terraform-aws-modules/terraform-aws-security-group#157]
Hi, I don't see anything in the examples or documentation that would allow us to add rules to an existing security group by using the existing group as a parameter.

Is this possible with this module?

**Comment by bryantbiggs** [comment]
hello @pfilbin90 could you provide an example - I'm not sure I fully understand what you are trying to achieve

**Comment by pfilbin90** [comment]
@bryantbiggs I am talking about utilizing this terraform resource:
https://www.terraform.io/docs/providers/aws/r/security_group_rule.html

Currently there are no modules on the Terraform registry that utilize it, so I am having to make my own that works alongside this security group module.

**Comment by bryantbiggs** [comment]
hi @pfilbin90 most of what you see in this module utilizes the `security_group_rule` as you referenced. perhaps if you have an example of what you are trying to achieve, I can help provide some direction

**Comment by TimJones** [comment]
@bryantbiggs probably the use of mutual security groups that was attempted to be fixed in #80

**Comment by bryantbiggs** [comment]
closed in https://github.com/terraform-aws-modules/terraform-aws-security-group/pull/218
