### ISSUE TITLE
Why do the prefix list rules have to be added to all rules?

### ISSUE THREAD

**Issue by pfilbin90** [terraform-aws-modules/terraform-aws-security-group#158]
For example:

```
egress_prefix_list_ids  = ["${data.terraform_remote_state.vpc.outputs.vpc_endpoint_s3_pl_id}"]
egress_with_source_security_group_id = [
    {
      rule                     = "mssql-tcp"
      description              = "Outbound SQL to EC2"
      source_security_group_id = module.ec2_apis_sg.this_security_group_id
    },
    {
      rule                     = "mssql-tcp"
      description              = "Outbound SQL"
      source_security_group_id = module.search_sg.this_security_group_id
    },
    {
      rule                     = "mssql-tcp"
      description              = "Outbound SQL to API Wrapper"
      source_security_group_id = module.this_sg.this_security_group_id
    }
]
```

This will now create 3 egress rules total for the prefix list.  But what if I just wanted 1 rule for the prefix list - going to 443?

**Comment by bryantbiggs** [comment]
hey @pfilbin90  I am not sure I follow - if you want only one rule then only create one rule, not three

**Comment by bryantbiggs** [comment]
looking again at your code you have 3 distinct security group IDs so 3 distinct rules will be created. this is not something the module controls, this is controlled by AWS

**Comment by pfilbin90** [comment]
@bryantbiggs I have the 3 distinct rules for security group IDs, yes.  But because I also included "egress_prefix_list_ids" as an input parameter, now I also have the module sending the prefix list to all 3 of those security groups individually.  My intent is just to have the port 443 have a destination preflix list, rather than having it go to specific SGs.

Does that make sense?

I guess what I really am looking for is an input parameter to the likes of "egress_with_source_prefix_list".  This is possible if you do it manually in the AWS console.
However, that doesn't appear to exist for this terraform module.

**Comment by tmattausch** [comment]
@pfilbin90 I agree that would be very nice. I just faced exact the same issue by using only the cidr blocks from these prefixes.


```
data "aws_prefix_list" "s3_private" {
  name = "com.amazonaws.eu-central-1.s3"
}

...

  egress_cidr_blocks       = data.aws_prefix_list.s3_private.cidr_blocks
  egress_rules              = ["https-443-tcp"]
```

**Comment by MartyFox** [comment]
With the release of the new prefix_list resources I wanted to reduce my overall rule count by using the customer managed lists. However as others have seen when I add a `prefix_list_id` into my security group, a rule is created for every port I add:

```hcl
module "example" {
  source = "terraform-aws-modules/security-group/aws"

  name        = "example"
  vpc_id      = module.vpc.vpc_id

  ingress_prefix_list_ids = [data.aws_ec2_managed_prefix_list.test.id]
  ingress_rules            = ["https-443-tcp"]
  
  ingress_with_cidr_blocks = [
    {
      rule        = "postgresql-tcp"
      cidr_blocks = "10.10.0.0/24"
    },
  ]
}
```

The above code will create 3 individual rules

Type | Protocol | Port range | Source | Description - optional
-- | -- | -- | -- | --
PostgreSQL | TCP | 5432 | 10.10.0.0/24 | Ingress Rule
PostgreSQL | TCP | 5432 | pl-01e2ebf3616d1 (test-prefix-list) | Ingress Rule
HTTPS | TCP | 443 | pl-01e2ebf3616d1 (test-prefix-list) | HTTPS

Looking at the module code I can see that `var.prefix_list_ids` is part of every rule resource which is what causes this to happen.

Does that mean its impossible to have rules for `security group id` alongside `prefix list id` without crossing over of the ports?
e.g. `security group A` can access this security group on port `443` only and `prefix list A` can access this security group on 8080 only

Type | Protocol | Port range | Source | Description - optional
-- | -- | -- | -- | --
HTTPS | TCP | 443 | security group A | HTTPS
HTTP | TCP | 8080 | prefix list A | HTTP
