### ISSUE TITLE
Does not (hopefully yet?) support Terraform 0.13.0-beta2

### ISSUE THREAD

**Issue by pfilbin90** [terraform-aws-modules/terraform-aws-security-group#177]
Currently Terraform 13 beta is not supported by this module.  Will this module eventually be updated to support it?  If so, what would the timeline be so that I can plan my stack upgrade around it?  Please let me know, thanks

**Comment by antonbabenko** [comment]
Good question.

I have just updated the version requirements in this module to stay forward-compatible with 0.13 release, and pushed [v3.11.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/v3.11.0) release. Please give it a try!

If you see anything not working in this module with Terraform 0.13, please open the issue.

---

This, as well as all other terraform-aws-modules, will be upgraded to work with Terraform 0.13 as soon as there is a request, a PR, or when Terraform 0.13 is released (hopefully, by the end of July).

I'd like to add that we (@terraform-aws-modules/triage-supporters and community at large) will try to keep modules working with little to no interruption and with backward-compatibility in mind.

**Comment by antonbabenko** [comment]
Already fixed.
