### ISSUE TITLE
Error: "Failed to Download Module" bad response code: 403

### ISSUE THREAD

**Issue by pfilbin90** [terraform-aws-modules/terraform-aws-security-group#188]
I am unable to download "terraform-aws-modules/security-group/aws".  I tried with both Terraform version 0.13.0 and 0.13.1 and I get the same error every time.
```
2020-08-27T19:41:56.2677529Z [0mCould not download module "alb-sec_groups"
2020-08-27T19:41:56.2678220Z source code from
2020-08-27T19:41:56.2679205Z "https://github.com/terraform-aws-modules/terraform-aws-security-group/archive/v3.16.0.tar.gz//*?archive=tar.gz":
2020-08-27T19:41:56.2680055Z bad response code: 403.
```

I've used this module for months with no issues so something must have changed on the backend.  

Module config below:

```
module "alb-sec_groups" {
    source = "terraform-aws-modules/security-group/aws"
    count               = var.build_green_app ? 1 : 0
    version = "~>3.16.0"

    name                   = "${var.env}-greenALB-sg"
    description            = "ALB security group"
    vpc_id                 = var.vpc_id

    ingress_with_cidr_blocks = [
    {
      from_port   = 443
      to_port     = 443
      description = "Inbound HTTPS to all"
      protocol    = "tcp"
      cidr_blocks = "0.0.0.0/0"
    }
  ]
  egress_with_cidr_blocks = [
    {
      from_port   = 443
      to_port     = 443
      description = "Outbound HTTPS to all"
      protocol    = "tcp"
      cidr_blocks = "0.0.0.0/0"
    }
  ]

  tags = "${merge(
    local.common_tags,
    map(
    "Name", "${var.env}-greenALB-sg"
    )
  )}"
}
```

**Comment by antonbabenko** [comment]
Hi,

There is an ongoing issue related to the Terraform Registry. I have received similar complaints from another user earlier today.

Also, this is probably related - https://status.hashicorp.com/incidents/z42xmmmjt0rm

Please ask general Terraform questions on discuss.hashicorp.com, and only questions related to this module in this repository.

Closing this one.

**Comment by pfilbin90** [comment]
@antonbabenko is there any ETA on the fix for this incident?  It has completely blocked me from being able to proceed with my projects.  There have been 0 updates since the incident has gone live.

**Comment by antonbabenko** [comment]
Unfortunately, I don't know anything about ETA for this incident. Please ask on discuss.hashicorp.com.

It is strange that this issue is still open for almost 24 hours already.
