### ISSUE TITLE
Getting "One of ['cidr_blocks', 'ipv6_cidr_blocks', 'self', 'source_security_group_id', 'prefix_list_ids'] must be set to create an AWS Security Group Rule" 

### ISSUE THREAD

**Issue by gugaiz** [terraform-aws-modules/terraform-aws-security-group#191]
I am trying to create a security group using 
```
module "app_db_sg" {
  source = "terraform-aws-modules/security-group/aws//modules/postgresql"

  name   = "${local.environment}-db-sg"
  vpc_id = module.vpc.vpc_id

  description = "Security group that controls access to DB"
  use_name_prefix = false

  computed_ingress_with_source_security_group_id = [
    {
      rule                     = "postgresql-tcp"
      source_security_group_id = module.app_beanstalk_environment.0.security_group_id
    }
  ]
  number_of_computed_ingress_with_source_security_group_id = 1
}
```
but I keep getting 
`Error: One of ['cidr_blocks', 'ipv6_cidr_blocks', 'self', 'source_security_group_id', 'prefix_list_ids'] must be set to create an AWS Security Group Rule`

I even tried with an static security group name (i.e. `"sg-02aexxxx56xxxx"` instead of `module.app_beanstalk_environment.0.security_group_id`) but it keeps failing the same way.

**Comment by valmack** [comment]
Same issue. I did this to get changes applied

```
module "security-group_grafana" {
  source  = "terraform-aws-modules/security-group/aws//modules/grafana"
  version = "3.12.0"

  name   = local.namespace
  vpc_id = var.vpc_id

  ingress_cidr_blocks = ["0.0.0.0/0"]  # <==== add this or one of the other options they list
}

```

**Comment by antonbabenko** [comment]
Thanks @valmack for the reply!

Also, you can always see examples of how each feature can be used. For instance, https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/examples/http/main.tf

Closing this issue.

**Comment by gugaiz** [comment]
@antonbabenko and @valmack  thanks for your replies, but I don't know to allow access to all IPs, I just need to allow access to one security group. I think I am following the examples but still not working.

**Comment by valmack** [comment]
> Thanks @valmack for the reply!
> 
> Also, you can always see examples of how each feature can be used. For instance, https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/examples/http/main.tf
> 
> Closing this issue.

Hi @antonbabenko unfortunately these examples are not helpful.

I also am trying to achieve the same thing as @gugaiz and it is not clear from any examples how to add one security group to another.

For example, I want to add grafana to my nfs security group, but I get the same error. Clearly I'm not understanding how to do this correctly. Can you explain what is wrong?

```
module "nfs_security_group" {
  source  = "terraform-aws-modules/security-group/aws//modules/nfs"
  version = "~> 3.0"

  name        = "${local.namespace}-nfs"
  vpc_id      = var.vpc_id

 source_security_group_id = "${module.grafana_security_group.this_security_group_id}"

  tags = local.default_tags
}
```

**Comment by himangshuj** [comment]
I am getting the same error, I think this is a bug 
```  cidr_blocks      = var.ingress_cidr_blocks
  ipv6_cidr_blocks = var.ingress_ipv6_cidr_blocks
  prefix_list_ids  = var.ingress_prefix_list_ids```
we do not have a variable called ingress_source_security_groups like we have for cidr_blocks

**Comment by baztian** [comment]
I also think that this should work without providing additional ingress cidr blocks. To make the module work I'm currently using

    module "service_sg" {
      source = "terraform-aws-modules/security-group/aws//modules/http-80"

      name        = "service-sg"
      description = "Security group for this service that allows being accessed from the ALB"
      vpc_id      = data.aws_vpc.default.id

      ingress_cidr_blocks = [data.aws_vpc.default.cidr_block]
      ingress_with_source_security_group_id = [
        {
          rule                     = "http-80-tcp",
          source_security_group_id = module.alb_sg.this_security_group_id
              },
      ]
    }

If I manually delete the cidr rule in aws console my setup still works as expected. @valmack can you please have another look into it? I would like to be able to only allow for access from a security group without opening up for the whole VPC.

**Comment by dtw45** [comment]
This seems to be caused by using a submodule as the source.
```hcl
  source = "terraform-aws-modules/security-group/aws//modules/postgresql"
```
If you use the root as your source, I believe it will work as expected.
```hcl
  source = "terraform-aws-modules/security-group/aws"
```
Perhaps it would be helpful to have an example that only declares a computed rule instead of also declaring `ingress_cidr_blocks` or similar.

**Comment by clayrisser** [comment]
I was getting this error . . .

```
Error: One of ['cidr_blocks', 'ipv6_cidr_blocks', 'self', 'source_security_group_id', 'prefix_list_ids'] must be set to create an AWS Security Group Rule
```
