### ISSUE TITLE
"...cidr_blocks" input vars require inconsistent formats

### ISSUE THREAD

**Issue by mjmenger** [terraform-aws-modules/terraform-aws-security-group#202]
ingress_cidr_blocks requires a list of CIDR strings

cidr_blocks within the ingress_with_cidr_blocks requires a comma-delimited string

please use the list type consistently, otherwise someone using your module will have to include unnecessary split() and join() calls.

**Comment by antonbabenko** [comment]
Hi,

This was the only solution back in the days when this module was created for Terraform 0.11.

If I write this module today it would be 70% shorter and more featureful (thanks to Terraform core features).

At the moment, I don't have immediate plans to rewrite it so there is not much we can do without breaking it for current users.

Closing this issue.

**Comment by mjmenger** [comment]
Fair enough. Thanks for the quick response.
