### ISSUE TITLE
Adding an item to ingress_rules triggers "duplicate security group rule" 

### ISSUE THREAD

**Issue by ecerulm** [terraform-aws-modules/terraform-aws-security-group#203]
If I add a rule to `ingress-rule` like this

```
  ingress_rules = [
    "https-443-tcp", # added this one
    "http-80-tcp",
    "http-8080-tcp",
    "https-8443-tcp",
    "all-icmp",
  ]
```

I will get 
```
Error: [WARN] A duplicate Security Group rule was found on (sg-xxx). This may be
a side effect of a now-fixed Terraform issue causing two security groups with
identical attributes but different source_security_group_ids to overwrite each
other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
information and instructions for recovery. Error message: the specified rule "peer: x.x.x.x/29, TCP, from port: 443, to port: 443, ALLOW" already exists
``` 

I believe this is caused because the way the indexes change `.aws_security_group_rule.ingress_rules[index]` which leads to terraform trying to 
* Modify the existing `all-icmp` to be `https-443`
* Create a new `all-icmp` 

instead of just adding a new `https-443`. 

This is the `terraform plan` output when I add `https-443` to `ingress_rules`: 

```
  # module.security_group_shared_services_allow_https_443_from_xxxx.aws_security_group_rule.ingress_rules[3] must be replaced
-/+ resource "aws_security_group_rule" "ingress_rules" {
        cidr_blocks              = [
            "x.x.x.x/29",
            "x.x.x.x/29",
            "x.x.x.x/8",
        ]
      ~ description              = "All IPV4 ICMP" -> "HTTPS"
      ~ from_port                = -1 -> 8443 # forces replacement
      ~ id                       = "sgrule-2257830919" -> (known after apply)
        ipv6_cidr_blocks         = []
        prefix_list_ids          = []
      ~ protocol                 = "icmp" -> "tcp" # forces replacement
        security_group_id        = "sg-xxx"
        self                     = false
      + source_security_group_id = (known after apply)
      ~ to_port                  = -1 -> 8443 # forces replacement
        type                     = "ingress"
    }
  + resource "aws_security_group_rule" "ingress_rules" {
      + cidr_blocks              = [
          + "x",
          + "x",
          + "1x",
        ]
      + description              = "All IPV4 ICMP"
      + from_port                = -1
      + id                       = (known after apply)
      + ipv6_cidr_blocks         = []
      + prefix_list_ids          = []
      + protocol                 = "icmp"
      + security_group_id        = "sg-xxx"
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = -1
      + type                     = "ingress"
    }
```

So I was able to  workaround this by adding the rule **at the end of ingress_rule**  but I don't think is a good general approach. Also deleting an ingress rules would be interpreted as modifying all ingress_rules below the one deleted, which make it difficult to review. 

**Maybe this could be solved by "indexing by name"  instead of with a numerical index?** I guess it's possible in current versions of terrraform that the resources would be `module.xxx.aws_security_group_rule.ingress_rules[all-icmp]` instead of `module.xxx.aws_security_group_rule.ingress_rules[3]`.  I suppose that would prevent terraform from interpreting adding a rule as modify all rules below. I believe this is proposed in #139

**Comment by ecerulm** [comment]
@antonbabenko , I'm pinging you because I'm not sure if the issues in `terraform-aws-security-group`  are monitored by anyone currently.

**Comment by antonbabenko** [comment]
Such change in index (from string to number) requires rewriting of the module and it will introduce a backward compatibility break. I don't think I will make it in the near future.

As you see, `ingress_rules` is not very powerful for the cases when you have competing rules trying to overwrite one another. Instead, you can use `ingress_with_cidr_blocks`, `ingress_with_source_security_group_id` or other variables with more verbose syntax where you will have bigger control. For example, https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/examples/complete/main.tf#L78-L94

**Comment by ecerulm** [comment]
I just tried with `ingress_with_cidr_blocks` and although it's still a lot of noise  with terraform reporting that all rules must be replaced , but it does **NOT** conflict so that is way better. 

```
ingress_with_cidr_blocks = [
    { // this is a new rule the other two already existed
      rule =     "activemq-61617-tcp",
      description = "rule3"
      cidr_blocks = "10.0.0.0/8"
    },
    {
      rule =   "activemq-5671-tcp",
      description = "rule1"
      cidr_blocks = "10.0.0.0/8"
    },
    {
      rule =   "activemq-61619-tcp"
      description = "rule2"
      cidr_blocks = "10.0.0.0/8"
    },
  ]
```

For terraform this becomes
* `xx.aws_security_group_rule.ingress_with_cidr_blocks[0]` must be replaced "rule1" -> "rule3" 
* `xx.aws_security_group_rule.ingress_with_cidr_blocks[1]` must be replaced "rule2" -> "rule1" 
* `xx.aws_security_group_rule.ingress_with_cidr_blocks[2]` will be created "rule2"  

But like I said it does **not conflict/duplicate like with `ingress_rules`** so I can't really complain that much. Thank you for point out this alternative 🙏.

Would it be possible to add a new `ingress_rules_named` (to not break compatibility)? I can look into writing a PR if you feel like is something feasible and you want to go in that direction.

**Comment by antonbabenko** [comment]
Good that it works for you!

Instead of adding even more variables like `ingress_rules_named` I would really prefer to have a solid refactoring and simplifications given we can use Terraform 0.13 features instead of relying on legacy Terraform 0.11 when this module was created at first.

Closing this issue.
