### ISSUE TITLE
computed_ingress_with_source_security_group_id not showing change. 

### ISSUE THREAD

**Issue by dogfish182** [terraform-aws-modules/terraform-aws-security-group#211]
## Description
Using terraform 0.13.5 seems to require the use of 

number_of_computed_ingress_with_source_security_group_id

parameter when attempting to use 

computed_ingress_with_source_security_group_id

even though to documentation seems to indicate that this was required in terraform 11 only. 

## Versions
0.13.5
 - Terraform: 0.13.5

 - Provider(s): registry.terraform.io/hashicorp/aws v3.35.0

 - Module: 4.0.0

## Reproduction

Steps to reproduce the behavior: Run a terraform plan when using 
computed_ingress_with_source_security_group_id
but not using 
number_of_computed_ingress_with_source_security_group_id

not using workspace

Local cache has been cleared issue persists.

### Code Snippet to Reproduce
```
module "efs_security" {
  source                                                   = "terraform-aws-modules/security-group/aws"
  version                                                  = "4.0.0"
  name                                                     = "sgp-test-group"
  computed_ingress_with_source_security_group_id           = [for rule in local.efs_rules : rule if rule.source_security_group_id != null && rule.type == "ingress"]
  tags                                                     = merge(var.project_tags, var.organisational_tags)
  vpc_id                                                   = data.aws_vpc.current.id
}

locals {
    efs_rules = [
    {
      type                     = "ingress",
      from_port                = 2049,
      to_port                  = 2049,
      protocol                 = "tcp",
      source_security_group_id = module.other_security_group.security_group_id
      self                     = false
      cidr_blocks              = null
      description              = "efs access"
    }
    ]
}
```

## Expected behavior

I would expect it would create a security group rule.

## Actual behavior

It does not create a security group rule. however if I supply number_of_computed_ingress_with_source_security_group_id it does work. I am using 0.13.5 and I understood that this param was to support terraform 11 and shouldn't be required.

**Comment by antonbabenko** [comment]
Probably bad wording in the docs.

It means that **starting from Terraform 0.11 and even in 0.15** the limitation is present and `number_of_computed_...` params are required.

See examples:
https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/f26887feb2af5dfd51ed19786eac20f2af8ba903/examples/computed/main.tf#L46-L53

**Comment by dogfish182** [comment]
Ah ok thanks for the clarification. I've found I can get terraform to play nice by using this construction without having to manually count things and use length of a local to keep the rules in order.

```
module "efs_security" {
  source                                                                                                         = "terraform-aws-modules/security-group/aws"
  version                                                                                                        = "4.0.0"
  name                                                                                                           = format("sgp-efs-%s", local.project)
  computed_ingress_with_source_security_group_id                       = local.efs_computed_ingress
  number_of_computed_ingress_with_source_security_group_id = length(local.efs_computed_ingress)
  tags                                                                                                              = merge(var.project_tags, var.organisational_tags)
  vpc_id                                                                                                          = data.aws_vpc.current.id
}

locals {
  efs_computed_ingress = [
    {
      from_port                = 2049
      to_port                  = 2049
      protocol                 = "tcp"
      description              = "efs"
      source_security_group_id = module.other_new_group.security_group_id
    },
  ]
}
```
