### ISSUE TITLE
[Docs] "Input variable" HTML tables are showing big blocks of empty space

### ISSUE THREAD

**Issue by boldandbusted** [terraform-aws-modules/terraform-aws-security-group#212]
Howdy. Thank you for your work here! I'm attaching a video (if I can) that shows the nature of the problem. I've tested in both Chrome and Firefox (latest versions) on Mac OS X 11.3.

I am excluding the other required Issue components because this report is solely about the README.md view. I hope this is okay. :)

https://user-images.githubusercontent.com/879972/116572466-fcf1b280-a8d9-11eb-909c-5f800b6a6988.mov

Happy to provide further info! :)

**Comment by antonbabenko** [comment]
Hi Jesse!

The issue you are referring to is related to the way how terraform-docs is rendering the information about inputs and outputs of the module.

I know it looks bad just on this module but I don't know how we can change it.

We use [terraform-docs](https://terraform-docs.io/) via [pre-commit-terraform hooks](https://github.com/antonbabenko/pre-commit-terraform).

Maybe we can pass some arguments to it in the config file - https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/.pre-commit-config.yaml#L6 ?
