### ISSUE TITLE
Implement `ingress_with_prefix_list_ids` and `egress_with_prefix_list_ids`

### ISSUE THREAD

**Issue by arielsalvo** [terraform-aws-modules/terraform-aws-security-group#224]
## Is your request related to a new offering from AWS?
This would be a missing use case related to the already implemented `ingress_prefix_list_ids` and `egress_prefix_list_ids`

## Is your request related to a problem? Please describe.
In order to create rules with different combinations of prefix_lists and ports in the same SG, I had to create rule-only modules and I even had to use `ingress_with_self` to create a rule for a custom port.

## Describe the solution you'd like.
The solution would be to implement something very similar to what is already implemented for other types of rules (e.g. `ingress_with_cidr_blocks` or `ingress_with_source_security_group_id`

## Describe alternatives you've considered.
As stated before, I created rule-only instances of the module to group by ports and prefix lists so that each prefix list can be granted access to the appropriate ports. i.e. list_A would have access to ports 443 and 22, and list_B only to port 443.

## Additional context
This is probably related to Issues #131 and #158 .

**Comment by arielsalvo** [comment]
This is still missing and shouldn't be closed

**Comment by simoferr98** [comment]
I find myself in the same situation. I ask that this issue be reappeared

**Comment by michaelallcloud** [comment]
Same here

**Comment by davcen** [comment]
Same problem here
