### ISSUE TITLE
I can't able to use this module for neptune port:8180

### ISSUE THREAD

**Issue by ravskoppula** [terraform-aws-modules/terraform-aws-security-group#227]
when I use this same for port 8180 ingress it's not working.

module "sg_mlops_ec2" {
  source      = "terraform-aws-modules/security-group/aws"
  version     = "4.3.0"
  name        = "${local.name}-ec2"
  description = "${local.name}-ec2 security group"
  vpc_id      = data.aws_vpc.vpc.id

  ingress_cidr_blocks = ["10.0.0.0/8"]
  ingress_rules       = ["http-80-tcp", "ssh-tcp", "all-icmp"]    # here if I change to "http-8180-tcp", its not working

  egress_cidr_blocks = ["0.0.0.0/0"]
  egress_rules       = ["all-all"]
}

**Comment by antonbabenko** [comment]
That's right, there is no named rule named "http-8180-tcp" in `var.rules`:

https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/3c7e1332d9e9f0628843b960782c2dd58c8709be/rules.tf#L7-L180

You need to specify a map with rule arguments like it is shown in [example](https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/examples/complete/main.tf).
