### ISSUE TITLE
create_before_destroy lifecycle block is only applied to name_prefix groups, not name only

### ISSUE THREAD

**Issue by Jess-Izen** [terraform-aws-modules/terraform-aws-security-group#231]
See [this issue](https://github.com/terraform-aws-modules/terraform-aws-security-group/issues/40) for background.

The lifecycle block for create_before_destroy is needed in order to properly delete and recreate security groups associated with load balancers. Otherwise, the initial destroy is blocked due to the attachment of the existing security group to the load balancer.

This module was patched to support this, but the fix currently only applies to name_prefix type groups. It works properly for resources of this type. However, it is not applied to the name group.

Can we apply this to both?

**Comment by antonbabenko** [comment]
No, we can't because it will fail to create a new SG with the same name before deleting an old one. That's why it is only available for `name_prefix` type groups.
