### ISSUE TITLE
Replace Inputs table with link to Terraform registry

### ISSUE THREAD

**Issue by sestrella** [terraform-aws-modules/terraform-aws-security-group#241]
Due to the large set of inputs and long default values like the one for `auto_groups` it makes the `Inputs` section on GitHub difficult to navigate since GitHub creates a long horizontal and vertical scrolling, therefore, replacing the whole table with a link to Terraform registry [inputs tab](https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/latest?tab=inputs) might make the README file more useful? Right now the `Inputs` section renders like this:

<img width="950" alt="image" src="https://user-images.githubusercontent.com/2049686/159302401-62b32aa7-8cf1-4ded-a282-e397a7a147b6.png">

I would be more than happy to submit a PR replacing the `Inputs` section with a link pointing to the Terraform registry.

**Comment by antonbabenko** [comment]
Hi @sestrella !

I completely agree that currently, the table doesn't look very nice.

Documentation is generated using [pre-commit-terraform](https://github.com/antonbabenko/pre-commit-terraform) that runs [terraform-docs](https://terraform-docs.io/). If you could find a way to configure `terraform-docs` to render this table in a better way, we can change it.

PR is welcome!
