### ISSUE TITLE
Port TCP/9096 not available

### ISSUE THREAD

**Issue by xcaliber-tech** [terraform-aws-modules/terraform-aws-security-group#244]
Hello,
Port TCP/9096 is no available . This port is used to communicate with brokers by using SASL/SCRAM.
https://docs.aws.amazon.com/msk/latest/developerguide/port-info.html
The same situation with TCP/9098

-- 
guzik

**Comment by officel** [comment]
hi @xcaliber-tech 

I'm sorry, I cannot give a proper desc or name.
But I think you should use this PR as a reference to create a new PR.
see https://github.com/terraform-aws-modules/terraform-aws-security-group/pull/186/files
