### ISSUE TITLE
Index issue while removing object in between of list

### ISSUE THREAD

**Issue by kapil1699** [terraform-aws-modules/terraform-aws-security-group#245]
Issue: I havr created SG with 4 inbound rules. variables for inbound rules is list in module.

Now if  I am removing 1st inbound rule from list the  terraform is saying tha it is going to destroy and create replacement.

Because now 2nd inbound rule comes to 1st in list that is the reason terraform is throwing that error.

How we can avoid this and remove safly without touching othet inbound rules.

Note:  I have 100+ inbound rule if I remove in between from list then it could create big problem of recreation.

I found one solution of using terraform state mv but moving each time  by running 100+ command seems tedious.

Please suggest.

**Comment by OuFinx** [comment]
Agree with @kapil1699 
I have the same troubles

**Comment by SolidSly** [comment]
In my opinion, the solution of this problem will be to switch the ingress / egress rules to a for_each system instead of using a list. However, this means that a part of the module should be updated to support this new pattern.

**Comment by antonbabenko** [comment]
@SolidSly You are right. We will have to do such an update and major rewrite of this module in the upcoming months. We already did it in some other modules under the `terraform-aws-modules` organization.

I am going to close this issue for now.
