### ISSUE TITLE
Submodules do not work correctly when used with `source_security_group_id`

### ISSUE THREAD

**Issue by chroju** [terraform-aws-modules/terraform-aws-security-group#265]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: v4.8.0

- Terraform version: v1.3.3

- Provider version(s): v4.37.0

## Reproduction Code [Required]

```hcl
module "efs_sg" {
  source  = "terraform-aws-modules/security-group/aws//modules/nfs"
  version = "v4.8.0"

  name        = "example-efs"
  vpc_id      = local.vpc_id
  description = "Security group allowing access to the EFS storage"

  ingress_with_source_security_group_id = [{
    rule                     = "nfs-tcp",
    source_security_group_id = "security_group_id"
  }]

  tags = local.tags
}
```

## Expected behavior

Terraform works fine. A security group is created that allows NFS access from the source security group.

## Actual behavior

Not working. `Error: One of ['cidr_blocks', 'ipv6_cidr_blocks', 'self', 'source_security_group_id', 'prefix_list_ids'] must be set to create an AWS Security Group Rule` .

## Additional context

This problem has been reported in the past.

* #191
* #193

These issues are closed, but I think this behavior is a bug that still exists or lacks documentation, so I reopened.

Submodules do not work correctly when used with `ingress_with_source_security_group_id`. This is due to the fact that `var.ingress_rules` is not empty. `"nfs-tcp"` is always included in the array.

https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/556f7c526df090cad34ade86227a731c485c88f9/modules/nfs/main.tf#L16

https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/556f7c526df090cad34ade86227a731c485c88f9/modules/nfs/auto_values.tf#L6-L10

`var.ingress_rules` is used here in the parent module. However, when specifying the `source_security_group_id` , it should not be necessary to create a resource `ingress_rules`.

https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/556f7c526df090cad34ade86227a731c485c88f9/main.tf#L66-L80

There are two workarounds for this behavior.

* When using `source_security_group_id` in a submodule, specify that the `auto_ingress_rules` variable should be empty `[]` .
* Do not use submodules.

Neither is mentioned in the documentation or examples. Either the code should be improved or the workarounds should be noted in the documentation.

**Comment by dynamike** [comment]
I tried to reproduce this issue, but am not seeing the issue you're reporting. Below is the sample terraform I used which is taken from what you listed above. 

```hcl
module "efs_sg" {
  source  = "terraform-aws-modules/security-group/aws//modules/nfs"
  version = "v4.8.0"

  name        = "example-efs"
  vpc_id      = "vpc-0a6f062234a403914"
  description = "Security group allowing access to the EFS storage"

  ingress_with_source_security_group_id = [{
    rule                     = "nfs-tcp",
    source_security_group_id = "sg-021894406c2636066"
  }]

}
```

and I couldn't reproduce it. This is also using the same terraform, aws provider, and module versions you listed. Is there something else that I'm missing?

**Comment by chroju** [comment]
Unfortunately, this works with aws provider v4, but seems to cause an error with v3. It was my environmental issue.
