### ISSUE TITLE
default egress are too permissive

### ISSUE THREAD

**Issue by joulaud** [terraform-aws-modules/terraform-aws-security-group#287]
## Description

Simple usage of your modules whitelist by default "all-all" as egress. This makes it complicated to use for composition of Security Group.

In my opinion all [egress_rules on rules.tf](https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/0093dcae5a918a44676ef3a2d7596b794fda11c0/rules.tf#L224-L516) should be empty.

- [X] ✋ I have searched the open/closed issues and a [comment](https://github.com/terraform-aws-modules/terraform-aws-security-group/issues/66#issuecomment-414140083) is related  but I don't understand the design decision here.

## Versions

- Module version [Required]: 4.17.1
- Terraform version: 1.4.6
- Provider version(s): 4.67.0

## Reproduction Code [Required]

```
module "ssh_security_group" {
  source  = "terraform-aws-modules/security-group/aws//modules/ssh"
  version = "4.17.1"

  description = "Allow ssh traffic to this instance"
  name        = "ssh"
  vpc_id      = (sensitive)

  ingress_cidr_blocks = [
    "0.0.0.0/0"
  ]
}
```

## Expected behavior

Only allow ingress ssh trafic when using this Security Group.

## Actual behavior

Also allow all egress trafic.

### Terminal Output Screenshot(s)

extract from `terraform state show`
```
resource "aws_security_group_rule" "egress_rules" {
    type              = "egress"
    description       = "All protocols"
    from_port         = 0
    to_port           = 0
    cidr_blocks       = [
        "0.0.0.0/0",
    ]
    ipv6_cidr_blocks  = [
        "::/0",
    ]
    protocol          = "-1"
}
```

## Additional context

I want to use your modules to compose easily several security-groups on some instances.

**Comment by antonbabenko** [comment]
You can change the rules to process by setting them to an empty list like this:
```hcl
module "ssh_security_group" {
  source  = "terraform-aws-modules/security-group/aws//modules/ssh"
  version = "4.17.1"

  description = "Allow ssh traffic to this instance"
  name        = "ssh"
  vpc_id      = (sensitive)

  ingress_cidr_blocks = [
    "0.0.0.0/0"
  ]

  egress_rules = []  # <- leave this empty
}
```
