### ISSUE TITLE
Creation of security group rules for RDS without CIDR results in zombie rules in terraform state

### ISSUE THREAD

**Issue by bhavith** [terraform-aws-modules/terraform-aws-security-group#296]
### Overview of the Issue
A [postgresql](https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/modules/postgresql/main.tf) module call to create a security group for allowing traffic to RDS instance using a source security group id always tries to create a rule with CIDR block as source.  Reference: https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/main.tf#L66 

This is because, the variable `ingress_rules` is automatically assigned a rule by the postgresql module and hence the `aws_security_group_rule` resource `ingress_rules` will be always created.

According to the docs, terraform expects a value for atleast one of the parameters `cidr_blocks, ipv6_cidr_blocks, prefix_list_ids` in the resouce `aws_security_group_rule`.  If we want the only source to be a security group, none of these are set.

It seems if none of these parameters are set,  apply doesn´t fail. Instead terraform creates a zombie resource in the state which is not mapped to any aws resource.

The state looks like this:
```
"attributes": {
            "cidr_blocks": [
              
            ],
            "description": "",
            "from_port": 5432,
            "id": "sgrule-xxxxxxxxx",
            "ipv6_cidr_blocks": [
              
            ],
            "prefix_list_ids": [
              
            ],
            "protocol": "tcp",
            "security_group_id": "sg-xxxxxxxxxxxxx",
            "security_group_rule_id": "",
            "self": false,
            "source_security_group_id": null,
            "timeouts": null,
            "to_port": 5432,
            "type": "ingress"
          },
```

Now this zombie resource´s description field is updated every time you make a change in the code resulting in unexpected changes in the plan which tries to set description from empty to `PostgreSQL` - the value set by  the postgresql module.

### Reproduction Steps
- Use the postgresql module to create security group and rules.
```
module "postgresql_security_group" {
  source  = "terraform-aws-modules/security-group/aws//modules/postgresql"
  version = "~> 5.0"

  name   = "For connecting to RDS"
  vpc_id = var.aws_vpc_id

  ingress_with_source_security_group_id = [
    {
      rule                     = "postgresql-tcp"
      source_security_group_id = var.source_security_group_id
    },
  ]
}
```

- Once applied,  run plan again.

# Expected Outcome:
There shouldn´t be any changes on the `ingress_rules` resource

# Actual Outcome
```
~ resource "aws_security_group_rule" "ingress_rules" {
      + description       = "PostgreSQL"
        id                = "sgrule-xxxxxxxxx"
        # (9 unchanged attributes hidden)
    }
```

# Impacted Versions:
Module version : `~> 5.0`
Provider version(s): `~> 5.4.0`

This issue is also visible in the Redis [module](https://github.com/terraform-aws-modules/terraform-aws-security-group/tree/master/modules/redis).

**Comment by remiflament** [comment]
I got similar issue using all the default values

```terraform
module "cluster_sg_postgresql" {
  source  = "terraform-aws-modules/security-group/aws//modules/postgresql"
  version = "5.1.0"

  name            = "xxxxxx"
  vpc_id          = data.aws_vpc.current.id
}
```

It's failing on the creation of the Postgres ingress rule
