### ISSUE TITLE
Module prompts for AWS region

### ISSUE THREAD

**Issue by brandonawells** [terraform-aws-modules/terraform-aws-security-group#31]
The AWS provider is included at the top of main.tf but is missing region information. For every copy of the module that I use, when I run terraform plan, i'm prompted to manually enter the region.

Can we remove the provide tag all together so that it uses whatever the user sets up in their own main.tf?

Example of prompt:

> Provider.aws.region
>   The region where AWS operations will take place. Examples
>   are us-east-1, us-west-2, etc.
> 
>   Default: us-east-1
>   Enter a value:

**Comment by antonbabenko** [comment]
You should specify `AWS_REGION` as an environment variable to get it to work. For example, `export AWS_REGION=eu-west-1`.

The majority of modules requires that developers specify env vars for AWS access and secret keys already.

**Comment by brandonawells** [comment]
Thanks

**Comment by otassetti** [comment]
Thanks for your answer Anton (I will search another solution since i can't use ENV vars in my use cases :-/ )

**Comment by antonbabenko** [comment]
@otassetti How do you set AWS access and secret keys now?

**Comment by 2solt** [comment]
Same here, Im setting it via variable:
```
provider "aws" {
  region  = "${var.aws_region}"
}
```

**Comment by otassetti** [comment]
@antonbabenko I use shared credential file, with several profile (using temporary session token populated with an external adfs script).

`~/.aws/credentials

[client1]
output = json
region = eu-west-1
aws_access_key_id = XXX
aws_secret_access_key = XX/XXX
aws_session_token = XXXXX


[client2]
output = json
region = eu-central-1
aws_access_key_id = YYY
aws_secret_access_key = YY/YYYY
aws_session_token = YYYY
...
`

**Comment by FernandoMiguel** [comment]
@otassetti when you do $ printenv is there a var for 
AWS_DEFAULT_REGION or AWS_REGION 
?

if you dont have those env vars set, TF wont pick them up

**Comment by otassetti** [comment]
@FernandoMiguel 
That's the the point, i'm using terraform for several client, and as i'm using differents auth profile, i can't cleanly handle the Region var using environnement as it is unique and very session/instance dependant, so i set it inside code.

`
/infra1/main.tf
Provider "aws" {
  profile                 = "client1
  shared_credentials_file = ""
  region                  = "eu-west-1"
}

/infra2/main.tf
Provider "aws" {
  profile                 = "client2
  shared_credentials_file = ""
  region                  = "eu-central-1"
}`

Thanks

**Comment by FernandoMiguel** [comment]
I always set it in the provider via variables.tf
```
provider "aws" {
  region = "${var.region}"

  assume_role {
    role_arn     = "arn:aws:iam::ACCOUNTID:role/OrganizationAccountAccessRole"
    session_name = "terraform"
  }
}
```
for auth, i use aws-auth
see if this helps
https://github.com/FernandoMiguel/kb/blob/master/aws/SetupMFA.md

my aws config looks like this
https://github.com/FernandoMiguel/kb/blob/master/aws/config

**Comment by antonbabenko** [comment]
I apologize for pushing this change a bit too fast (I did never like it myself). I will revert this PR in a few minutes and write a blog post about it soon.

**Comment by antonbabenko** [comment]
Reverted as [v1.11.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/tree/v1.11.0).

**Comment by antonbabenko** [comment]
https://medium.com/@anton.babenko/providers-version-in-terraform-modules-ab35b47a3d14
