### ISSUE TITLE
auto_groups default value in the readme is huge

### ISSUE THREAD

**Issue by madpipeline** [terraform-aws-modules/terraform-aws-security-group#311]
## Description

The default value for the `auto_groups` is so large that it makes the README.md basically unreadable.

My initial thought was that the inputs table is empty, but after I scrolled for some time, I found there is content there.

Perhaps the default contents of this variable should be documented in a separate file?

**Comment by antonbabenko** [comment]
We've had similar issues reported in the past.

If you find out how to tweak `terraform-docs` in GitHub Actions to render it better, please open a PR.
