### ISSUE TITLE
Update required providers version

### ISSUE THREAD

**Issue by Jamaca1410** [terraform-aws-modules/terraform-aws-security-group#316]
## Description

AWS terraform provider is now on ~> 5.65.0, but this modules still uses >= 3.29.0 this could be improved as small security enhances.

## Versions

- Module version [Required]: 5.1.1

- Terraform version: 1.7.4

- Provider version(s): 5.65.0

## Reproduction Code [Required]

- Run `terraform init -upgrade` with latest AWS providers

## Expected behavior

Module use latest AWS provider measure.

## Actual behavior

Dependency miss match from my config and module provider version.

### Terminal Output Screenshot(s)
<img width="538" alt="Screenshot 2024-03-07 at 13 19 52" src="https://github.com/terraform-aws-modules/terraform-aws-security-group/assets/69948122/d0f1b364-b467-4870-a6cc-fd47684acc45">

**Comment by ananthmkashyap** [comment]
Hi,

Please correct me if I'm wrong but the latest terraform provider version is v5.40.0.
-> https://releases.hashicorp.com/terraform-provider-aws/

**Comment by antonbabenko** [comment]
@Jamaca1410

`this modules still uses >= 3.29.0` - or, is better to say that `this module requires Terraform AWS provider version higher than 3.29.0`.

Bumping this requirement is only necessary if we use features of the later provider version.
