### ISSUE TITLE
Security group rule is not removed

### ISSUE THREAD

**Issue by garym-krrv** [terraform-aws-modules/terraform-aws-security-group#322]
## Description

When changing  the rule in egress_with_cidr_blocks, the orignal rule does not get removed from the security group even though the terraform says its been destroyed. Removing a rule from the variable forces the rule to be deleted, but just changing the rule value in the map eg from dns-tcp to all-all doesnt remove the old rule, but creates a new rule.

If your request is for a new feature, please use the `Feature request` template.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Running from spacelift
## Versions

- Module version 5.1.2:

- Terraform version:
1.5.7

- Provider version(s):
aws 5.30, 5.55

## Reproduction Code [Required]

```
module "complete_sg" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "5.1.2"

  name        = "testsg"
  description = "test"
  vpc_id      = module.vpc-main.vpc_id

  tags = {
    Name = "test.sg"
  }


  # Open to CIDRs blocks (rule or from_port+to_port+protocol+description)
  ingress_with_cidr_blocks = [
    {
      rule        = "postgresql-tcp"
      cidr_blocks = "0.0.0.0/0,2.2.2.2/32"
    },
    {
      rule        = "postgresql-tcp"
      cidr_blocks = "30.30.30.30/32"
    },
    {
      from_port   = 10
      to_port     = 20
      protocol    = 6
      description = "Service name"
      cidr_blocks = "10.10.0.0/20"
    },
  ]

  egress_cidr_blocks = ["10.10.0.0/16"]

  egress_ipv6_cidr_blocks = ["2001:db8::/64"]

  egress_with_cidr_blocks = [
    {
      rule        = "openvpn-tcp"
      cidr_blocks = "0.0.0.0/0"
    }       
  ]


  create_timeout = "15m"
  delete_timeout = "45m"
}

```

to 

```
module "complete_sg" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "5.1.2"

  name        = "testsg"
  description = "test"
  vpc_id      = module.vpc-main.vpc_id

  tags = {
    Name = "test.sg"
  }


  # Open to CIDRs blocks (rule or from_port+to_port+protocol+description)
  ingress_with_cidr_blocks = [
    {
      rule        = "postgresql-tcp"
      cidr_blocks = "0.0.0.0/0,2.2.2.2/32"
    },
    {
      rule        = "postgresql-tcp"
      cidr_blocks = "30.30.30.30/32"
    },
    {
      from_port   = 10
      to_port     = 20
      protocol    = 6
      description = "Service name"
      cidr_blocks = "10.10.0.0/20"
    },
  ]

  egress_cidr_blocks = ["10.10.0.0/16"]

  egress_ipv6_cidr_blocks = ["2001:db8::/64"]

  egress_with_cidr_blocks = [
    {
      rule        = "all-all"
      cidr_blocks = "0.0.0.0/0"
    }       
  ]


  create_timeout = "15m"
  delete_timeout = "45m"
}

```

Update variable as follows 

FROM
```
  egress_with_cidr_blocks = [
    {
      rule        = "openvpn-tcp"
      cidr_blocks = "0.0.0.0/0"
    }       
  ]
```

to

```
  egress_with_cidr_blocks = [
    {
      rule        = "all-all"
      cidr_blocks = "0.0.0.0/0"
    }       
  ]
```
## Expected behavior

Old rule to be deleted and new one created

## Actual behavior

New rule created old rule remains

**Comment by jd-ucpa** [comment]
Hi @garym-krrv 

The `ingress` and `egress` arguments are processed in [attributes-as-blocks](https://developer.hashicorp.com/terraform/language/attr-as-blocks) mode. Due to this, removing these arguments from the configuration **will not** cause Terraform to destroy the managed rules.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#removing-all-ingress-and-egress-rules

**Comment by garym-krrv** [comment]
Arh thank you very much.. Never knew this..

**Comment by jd-ucpa** [comment]
Yes, I just make some tests with TF and the results are stanges :
if you add, for ex, 3 ingress bloc, then tf apply.
Tf will add the 3 inbound rules

If you remove (comment) 1 or 2 ingress bloc, then tf plan (to see)
Tf will say : i plan to remove A or 2 blocs
So everything is ok

But you comment the 3 ingresq bloc, then tf plan (to see)
Tf will say, nothing to do : 'Your infrastructure matches the configuration'
What ?!

So if you want to remove all
ingress = []

But if don't forget this strange behavior too
