### ISSUE TITLE
Switch to using aws_vpc_security_group_egress_rule and aws_vpc_security_group_ingress_rule

### ISSUE THREAD

**Issue by mhowell-ims** [terraform-aws-modules/terraform-aws-security-group#323]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: available since 4.56.0

## Is your request related to a problem? Please describe.
These newer resources types now seem to be the recommended way to create SG rules. Excerpt from the docs for these newer resources:

Terraform currently provides a [Security Group resource](https://registry.terraform.io/providers/hashicorp/aws/4.56.0/docs/resources/security_group) with ingress and egress rules defined in-line and a [Security Group Rule resource](https://registry.terraform.io/providers/hashicorp/aws/4.56.0/docs/resources/security_group_rule) which manages one or more ingress or egress rules. Both of these resource were added before AWS assigned a [security group rule unique ID](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-rules.html), and they do not work well in all scenarios using the description and tags attributes, which rely on the unique ID. The aws_vpc_security_group_egress_rule resource has been added to address these limitations and should be used for all new security group rules. You should not use the aws_vpc_security_group_egress_rule resource in conjunction with an aws_security_group resource with in-line rules or with aws_security_group_rule resources defined for the same Security Group, as rule conflicts may occur and rules will be overwritten.

## Describe the solution you'd like.
Switch to using these newer resource types for the rules instead of the older one, or perhaps provide an option to choose which ones to use.

**Comment by phene** [comment]
This is a legit issue and I won't be using this module because it uses deprecated resources.

**Comment by mhowell-ims** [comment]
@antonbabenko I also believe this is a legit issue, can this be re-opened?

**Comment by Omicron7** [comment]
We just ran into this issue as well. Switching the module to use the newer resources would fix the issue of a race condition when changing/adding/removing CIDRs from a `cidr_blocks`.

**Comment by mhowell-ims** [comment]
Yes we have run into that race condition as well, it has been very disruptive for us at times. I don't see an option to re-open this issue, I wish I could! @antonbabenko can you re-open this issue?
