### ISSUE TITLE
Ingress with source sg id fails

### ISSUE THREAD

**Issue by RupertExact** [terraform-aws-modules/terraform-aws-security-group#36]
I'm pretty sure this should work but I end up with an error. 

> module.data_tier.module.sg_sql_clients.aws_security_group_rule.ingress_with_source_security_group_id: aws_security_group_rule.ingress_with_source_security_group_id: value of 'count' cannot be computed

Am I missing something obvious?

`module "sg_tux_sql" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "1.13.0"

  name   = sg-tux-sql"
  create = true
  vpc_id = "${var.vpc_id}"

  ingress_with_source_security_group_id = [
    {
      from_port                = 1433
      to_port                  = 1434
      protocol                 = "tcp"
      description              = "MS SQL"
      source_security_group_id = "${module.sg_sql_clients.this_security_group_id}"
    },
  ]

  egress_rules       = ["all-all"]
  egress_cidr_blocks = ["0.0.0.0/0"]

}`

**Comment by antonbabenko** [comment]
Unfortunately, you are absolutely right - it should work. This is a known limitation, see [this note](https://github.com/terraform-aws-modules/terraform-aws-security-group#1-security-group-with-custom-rules).

**Comment by antonbabenko** [comment]
This is now fixed in [v2.0.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/v2.0.0). See this section in [README](https://github.com/terraform-aws-modules/terraform-aws-security-group#note-about-value-of-count-cannot-be-computed)
