### ISSUE TITLE
Create integration tests using kitchen-terraform

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/terraform-aws-security-group#4]
I think this repository is a good example where we can start creating integration tests for Terraform AWS modules using [kitchen-terraform](https://github.com/newcontext-oss/kitchen-terraform) because this module creates resources which can be asserted without dependencies.

I am also thinking about these requirements:
1. All tests files (incl. `Gemfile`, `.kitchen.yml` and alike) should be outside of the root directory. Let's put everything inside `tests` directory with subdirectories as necessary.
1. Alternatively to point 1 (above) build Docker image (eg, [Dockerfile](https://github.com/antonbabenko/terrapin/blob/master/.circleci/images/antonbabenko/terrapin/Dockerfile)) containing all dependencies required to run kitchen-terraform
1. Tests should execute code/fixtures which is inside directory `examples/http` as is (without modification). The same code can always be executed by a user who wants to run examples manually using just basic commands.
1. Use CircleCI 2.0 (CircleCI 2.0 is terribly fast and customisable).

@ncs-alane - Do you think such structure can be easily achieved with kitchen-terraform?

Do you have an opportunity&wish to submit initial PR for this?

**Comment by ncs-alane** [comment]
@antonbabenko sorry, I missed your question here!

1. This should be possible: Test Kitchen supports alternate paths to `.kitchen.yml`
2. Would this image be specific to each project or just a package of kitchen-terraform?
3. This is also possible, though less conventional than `test/integration`. What do you mean by "without modification"?
4. I have not investigated CircleCI yet, but if it supports arbitrary downloads, command execution, and making SSH connections then it should be acceptable

I think we can find some one from @newcontext-oss that would be willing to take this on.

**Comment by roman-cnd** [comment]
This also can be useful: https://github.com/k1LoW/awspec
https://github.com/elmundio87/terraform_validate
