### ISSUE TITLE
Rules lists gives 404 error.

### ISSUE THREAD

**Issue by RobotLimeLtd** [terraform-aws-modules/terraform-aws-security-group#46]
I get a 404 when I try to visit the link:  https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/rules.tf

Has this file moved?

**Comment by antonbabenko** [comment]
The file is still [there](https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/rules.tf), but links are relative, so they don't work properly on [registry.terraform.io](https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws)

**Comment by antonbabenko** [comment]
[v1.20.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/tag/v1.20.0) has been released and I fixed all broken links there. Please open a new issue or submit a PR if you spot something wrong.
