### ISSUE TITLE
Is there any plan to solve the dependencies between Security groups

### ISSUE THREAD

**Issue by mvives-broadsign** [terraform-aws-modules/terraform-aws-security-group#48]
Hi Guys, 
I am starting to write terraform scripts for my company and I am wondering if there is any plan (in this module, I am not yet familiar enough with terraform to understand the inner issue) to solve this issue: https://github.com/terraform-aws-modules/terraform-aws-security-group/issues/16

It's quite an issue here because it means we either have to manage security groups outside terraform (aws cli for example) and use them as data resources in tf (but it means we also have to properly track them and destroy them if need be ) or we need to run terraform apply multiple times with added lines in the script (which might also be very error prone)

I am hitting the issue because I want to allow connections from a sg to another sg, but if I understand correctly, I will run into it also when I will want to add ec2 containers inside sg. (all my sg have a vpc_id that is computed)

**Comment by FernandoMiguel** [comment]
Yes, you can do it in two state files, run first in to create the SG and
then a second state run to create the rules.

Newer versions of tf do allow for modules to depend on the output of
another module which in some cases works around this issue.
I have a VPC module I actually need to redo to test this

--
Fernando Miguel

**Comment by antonbabenko** [comment]
I have just released [v2.0.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/v2.0.0) where it is now possible to reference computed values.
