### ISSUE TITLE
How to use a list variable as input for cidr_blocks within ingress_with_cidr_blocks ?

### ISSUE THREAD

**Issue by levequej** [terraform-aws-modules/terraform-aws-security-group#50]
Maybe this is a know limitation I'm not aware of but I can't use a compted list as input for cidr_blocks within ingress_with_cidr_blocks

* module.my_mod.module.my_sg.aws_security_group_rule.ingress_with_cidr_blocks: lookup: lookup() may only be used with flat maps, this map contains elements of type list in:

${split(",", lookup(var.ingress_with_cidr_blocks[count.index], "cidr_blocks", join(",", var.ingress_cidr_blocks)))}
  

ingress_with_cidr_blocks = [
    {
      from_port   = 3000
      to_port     = 3000
      protocol    = "tcp"
      description = "NodeJSPort"
      cidr_blocks = ["${var.my_cidr_blocks}"]
    },
  ]

with 
variable "my_cidr_blocks" {
  default = [
    "10.0.0.0/8",
    "192.168.0.0/16",
    "172.16.0.0/16",
  ]
}

**Comment by antonbabenko** [comment]
Yes, computed lists are not supported in Terraform yet, but also AWS keeps EC2 security group rules linearly (no lists of IPs).

The best solution to your problem is to split one list into several maps like this:
```
  ingress_with_cidr_blocks = [
    {
      from_port = 3000
      to_port = 3000
      protocol = "tcp"
      description = "NodeJSPort"
      cidr_blocks = "10.0.0.0/8"
    },
    {
      from_port = 3000
      to_port = 3000
      protocol = "tcp"
      description = "NodeJSPort"
      cidr_blocks = "192.168.0.0/16"
    },
    {
      from_port = 3000
      to_port = 3000
      protocol = "tcp"
      description = "NodeJSPort"
      cidr_blocks = "172.16.0.0/16"
    },
  ]
```

Hope it helps.

**Comment by levequej** [comment]
thanks
