### ISSUE TITLE
Issue when configuring ingress_with_cidr_blocks from a remote state

### ISSUE THREAD

**Issue by teamhanded** [terraform-aws-modules/terraform-aws-security-group#54]
Hi there.

I'm using [this](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/1.26.0) AWS VPC module to create a VPC and the subnets, and I'm creating this output for the private subnets CIDR blocks.

```
output "private-subnets" {
  value = "${module.main-vpc.private_subnets_cidr_blocks}"
}
```

Which generates this, when I run **terragunt apply**

```
Outputs:

private-subnets = [
    172.19.101.0/24,
    172.19.102.0/24
]
```

However, when configuring the **ingress_cidr_blocks** variable in the security groups module

`ingress_cidr_blocks = "${data.terraform_remote_state.vpc-private-cidrs.private-subnets}"`

I get this error:

```
* module.eks-worker-security-group.aws_security_group_rule.ingress_with_cidr_blocks: lookup: lookup() may only be used with flat maps, this map contains elements of type list in:

${split(",", lookup(var.ingress_with_cidr_blocks[count.index], "cidr_blocks", join(",", var.ingress_cidr_blocks)))}
```

I don't understand why this happens. Questions:

* Should I format the output to generate a map instead of a list?
* Given that I'm taking the output from a terraform_remote_state datasource, which is supposed to be known and not calculated, shouldn't the invocation be working?
* What can I do for those subnets to be accepted by **ingress_with_cidr_blocks**?

Thanks!

**Comment by teamhanded** [comment]
@antonbabenko Any input will be much appreciated!

**Comment by antonbabenko** [comment]
Sorry for the delay. I didn't have too much time lately. Briefly speaking the best idea is to reuse CIDR blocks which you pass to VPC module to security-group module as a type of list. This way you avoid using not-calculated values, which is currently not supported well in Terraform.

If you can show your code how you invoke both modules and providing arguments I can probably help more.

Also, you don't need to use `split()` and `lookup()` as you mentioned, because modules accept proper `list` and don't need a comma-magic.

**Comment by teamhanded** [comment]
Thanks. :)

I have a VPC module which tfstate is written to a S3 module. Once I apply the changes, it generates the output mentioned in the first comment. This is how I'm calling the value:

```
#Map the VPC private subnets stored in S3 bucket so we can call them later
data "terraform_remote_state" "vpc-private-cidrs" {
  backend = "s3"

  config {
    bucket = "my-unique-bucket"
    region = "us-west-2"
    key    = "cluster/vpc/${var.cluster_environment}/terraform.tfstate"
  }
}

module "security-group" {
  source = "terraform-aws-modules/security-group/aws"

  name        = "my security group"
  description = "Generated by Terraform"
  vpc_id      = "${data.terraform_remote_state.vpc-private-cidrs.vpc-id}"
  ingress_cidr_blocks = ["${data.terraform_remote_state.vpc-private-cidrs.private-subnets}"]

  ingress_with_cidr_blocks = [
    {
      from_port   = 0
      to_port     = 0
      protocol    = "-1"
      self        = false
      description = "Open access"
      cidr_blocks = ["${data.terraform_remote_state.vpc-private-cidrs.private-subnets}"]
    },
  ]
}
```

The output is correctly generated by Terraform, and available for use:

```
Outputs:

private-subnets = [
    172.19.101.0/24,
    172.19.102.0/24
]
```

The outputs.tf file for the vpc module is as follows.

```
output "private-subnets" {
  value = "${module.main-vpc.private_subnets_cidr_blocks}"
}

output "vpc-id" {
  value = "${module.main-vpc.vpc_id}"
}
```

Given that the CIDR values are part of a Terraform state, they shouldn't be interpreted as pre-computed. I'm just trying to understand what's missing here. 

Note: I'm using Terragrunt.

**Comment by antonbabenko** [comment]
I think I know where the problem is. Terraform doesn't work well with data types like `list of maps`, so that is why there is a hack with commas on this line - https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/d1a00102409adb03fbc2111a6c58f84e437c2920/examples/complete/main.tf#L123

Wrap it with `join` like this:
```hcl
cidr_blocks = "${join(",", data.terraform_remote_state.vpc-private-cidrs.private-subnets)}"
```

**Comment by teamhanded** [comment]
That actually worked!  Thanks, Anton. I'm now able to pull the CIDRs from the remote state. <3

**Comment by antonbabenko** [comment]
Nice!

**Comment by sivanagireddyb** [comment]
how to get security id from state file?

**Comment by SivaBu-kore** [comment]
@antonbabenko Got it. Cant, we get values other than outputs from state files as they are JSON formatted?

**Comment by antonbabenko** [comment]
Everything is possible. Please check official documentation for Terraform.
