### ISSUE TITLE
Access to this_security_group_id

### ISSUE THREAD

**Issue by TinajaLabs** [terraform-aws-modules/terraform-aws-security-group#6]
I think this is more of a terraform question but I'm not getting much feedback on the terraform group.

I'm using this module, and I'm also using the terraform-aws-ec2-instance.

In the terraform-aws-ec2-instance module I want to access this_security_group_id but I cannot see the way forward.  I added:

`variable "this_security_group_id" {} `

to the input variables file of terraform-aws-ec2-instance but it doesn't see the output variable value of terraform-aws-security-group.

Any help is appreciated.

**Comment by antonbabenko** [comment]
I have just updated example of [terraform-aws-ec2-instance](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/master/examples/basic/main.tf) which should answer your question. Let me know if you still have any question.

**Comment by TinajaLabs** [comment]
My problem is described in more detail here:  [Variable scope problem... modules](https://groups.google.com/forum/#!topic/terraform-tool/u0-aK8GJi1g)

Your solution, to use `vpc_security_group_ids` and do it in the same level, looks encouraging.  I will try it in the morning.  

Thank you,
Chris.

**Comment by antonbabenko** [comment]
Also, as [suggested](https://groups.google.com/d/msg/terraform-tool/u0-aK8GJi1g/hYDNtHhHAAAJ) you should use remote state data source if you want to read other resources properties created in another layer (directory).
