### ISSUE TITLE
module fails silently to create inbound rules

### ISSUE THREAD

**Issue by pydo** [terraform-aws-modules/terraform-aws-security-group#64]
**Description**
I am unable to create a security with inbound rule using this module.

**Repro steps**
1. create the following file: `main.tf`
```
module "security_group" {
  source = "terraform-aws-modules/security-group/aws"

  name = "terraform-bastion-security-group"
  vpc_id = "${module.vpc.vpc_id}"
  description = "Security group that allows devs to connect to private EC2 subnets"

  ingress_cidr_blocks = [
    {
      cidr_blocks = "173.138.148.14/32"
      description = "office"
      rule = "ssh-tcp"

    },
    {
      cidr_blocks = "134.140.91.119/32"
      description = "home2"
      rule = "ssh-tcp"
    },
    {
      cidr_blocks = "162.126.201.144/32"
      description = "home1"
      rule = "ssh-tcp"
    }
  ]

  tags = {
    Terraform = "true"
    Environment = "test"
  }
}
```
I've excluded the `vpc` module code because it doesn't seem relevant to my issue.

2. `terraform plan -out=plan.out`
3. `terraform apply plan.out`

**Expected behavior**
The security group is created 3 inbound rules.

**Actual behavior**
The security group is created without any inbound rules.

**Notes**
Terraform doesn't output any warnings/errors, so it would appear that my usage if the module is valid.

**Comment by pydo** [comment]
Replacing `ingress_cidr_blocks` with `ingress_with_cidr_blocks` solved my problem. But I still think it's a problem that this module doesn't complain/verify any additional arguments it receives.

**Comment by antonbabenko** [comment]
Great that you managed to fix your problem.

You are right that it would be great if this module verifies all arguments it receives and complains earlier but I don't know how to make it so that the code of this module would be still maintainable and flexible. If you have ideas you are welcome.

**Comment by pydo** [comment]
@antonbabenko Maybe I am expecting too much from terraform, since it uses it's own custom DSL. I'd expect argument validation from a general purpose programming language, but as you say it might be difficult to do it in a clean/maintainable way.

**Comment by antonbabenko** [comment]
Your suggestion makes perfect sense for the upcoming version of Terraform where validation will be possible to implement in an easier way. Meanwhile, we have what we have.

We will get back to this issue in a couple of months in a more systematic manner (across large amount of repositories), so I am closing this issue for now.

Please don't hesitate to open other issues if you see something very wrong.
