### ISSUE TITLE
Unexpected IPv6 egress rule added.  

### ISSUE THREAD

**Issue by thecommandline** [terraform-aws-modules/terraform-aws-security-group#66]
The following implementation of this module creates an egress rule for HTTP with a destination of ::/0. Is this to be expected? If I remove the two egress lines then there are no egress rules for either IPv4 or IPv6. When I add them back I get the expected IPv4 rules and the unexpected IPv6 rule.

    module "load_balancer_sg" {
      source = "terraform-aws-modules/security-group/aws"
    
      name   = "load-balancer"
      vpc_id = "${module.vpc.vpc_id}"
    
      ingress_rules       = ["http-80-tcp", "https-443-tcp"]
      ingress_cidr_blocks = ["0.0.0.0/0"]
      egress_rules        = ["http-80-tcp"]
      egress_cidr_blocks  = "${var.private_subnets}"
    }

    variable private_subnets {
      type    = "list"
      default = ["10.0.11.0/24", "10.0.12.0/24", "10.0.13.0/24"]
    }

**Comment by antonbabenko** [comment]
You should override value of `egress_ipv6_cidr_blocks` with an empty list. Like this - `egress_ipv6_cidr_blocks = []`.

This was the design decision to have `egress` CIDR blocks wide open while `ingress` is restricted.
