### ISSUE TITLE
Adding egress_cidr_block entry does not change infrastructure

### ISSUE THREAD

**Issue by pydo** [terraform-aws-modules/terraform-aws-security-group#68]
Adding a `egress_cidr_blocks` to the security group module does not cause terraform to detect any changes.

**Repro**
1. Create a security group
ex:
 ```
module "security_group" {
  source = "terraform-aws-modules/security-group/aws"
  name = "sec-grp1"
  vpc_id = "${module.vpc.vpc_id}"
  ingress_cidr_blocks = [
    "35.192.136.167/32",
    "147.75.192.163/32"]
  ingress_rules = ["ssh-tcp"]
}
```
2. Plan and apply the resource using terraform
3. Add follow key to the security group   `egress_cidr_blocks = ["0.0.0.0/0"]`
4. Run `terraform plan -out=plan.out`

**Expected behavior**
Terraform detects a change to the security group resource

**Actual behavior**
Terraform does not detect any changes:
```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

**Comment by antonbabenko** [comment]
You need to specify both - `egress_rules` and `egress_cidr_blocks`, like this:
```hcl
  egress_rules = ["all-all"] # see rules.tf for the complete list of rules
  egress_cidr_blocks = ["0.0.0.0/0"]
```
