### ISSUE TITLE
No rules created when using `computed_ingress_with_source_security_group_id`

### ISSUE THREAD

**Issue by pydo** [terraform-aws-modules/terraform-aws-security-group#72]
**Description**
No inbound rules are created when using `computed_ingress_with_source_security_group_id`

**Repro steps**
1. Example terraform security group:
```
module "mysql_wordpress_security_group" {
  source = "terraform-aws-modules/security-group/aws"

  name = "mysql_wordpress_security_group"
  vpc_id = "${module.vpc.vpc_id}"
  description = "test"

  computed_ingress_with_source_security_group_id = [
    {
      source_security_group_id = "${module.ec2_security_group.this_security_group_id}"
      rule = "mysql-tcp"
    }
  ]
  egress_cidr_blocks = ["0.0.0.0/0"]
  egress_rules = ["all-all"]


  tags = {
    Terraform = "true"
    Environment = "${terraform.workspace}"
  }
}
```
2. `terraform plan` & `terraform apply`

**Expected behavior**
A security group with an inbound rule is created

**Actual behavior**
A security group without any inbound rules is created.

**Comment by pydo** [comment]
I found the relevant documentation about my issue.
I need to specify the number of security groups to created.
`number_of_computed_ingress_with_source_security_group_id = 1`
Maybe this issue can be converted into a future improvement where the `number_of_computed_ingress_with_source_security_group_id` could be computed dynamically?

**Comment by antonbabenko** [comment]
Yes, as you have found out, `number_of_computed_...` type of arguments were added exactly to solve the limitation with computed values in Terraform 0.11. It will become unnecessary in Terraform 0.12.
