### ISSUE TITLE
aws_security_group_rule.ingress_rules: One of ['cidr_blocks', 'ipv6_cidr_blocks', 'self', 'source_security_group_id', 'prefix_list_ids'] must be set to create an AWS Security Group Rule

### ISSUE THREAD

**Issue by veilig2000** [terraform-aws-modules/terraform-aws-security-group#75]
I'm getting errors trying to setup my module w/ ingress_with_cidr_blocks

```
Error: Error applying plan:

1 error(s) occurred:

* module.web_server_sg.module.sg.aws_security_group_rule.ingress_rules: 1 error(s) occurred:

* aws_security_group_rule.ingress_rules: One of ['cidr_blocks', 'ipv6_cidr_blocks', 'self', 'source_security_group_id', 'prefix_list_ids'] must be set to create an AWS Security Group Rule

```

I understand the ingress_with_cidr_blocks is not an option listed in the error, but I'm going off the [comment](https://github.com/terraform-aws-modules/terraform-aws-security-group/issues/65#issuecomment-400191600) from a previous issue that said this would be ok.  I have a pretty bare example of the failure, am I forgetting/missing adding something to my module?

```
provider "aws" {
  version = "~> 1.31.0"
  alias  = "us-west-1"
  region = "us-west-1"
  profile = "${var.profile}"
}

data "terraform_remote_state" "vpc" {
  backend = "s3"

  config {
    bucket = "${var.vpc_remote_state_bucket}"
    key    = "${var.vpc_remote_state_key}"
    region = "${var.region}"
    profile = "${var.profile}"
  }
}

module "web_server_sg" {
  source = "terraform-aws-modules/security-group/aws//modules/http-80"

  name        = "web-server"
  vpc_id      = "${data.terraform_remote_state.vpc.us_east_vpc1_id}"

  ingress_with_cidr_blocks = [
      {
          "rule" = "http-80-tcp"
          "cidr_blocks" = "0.0.0.0/0"
      },
  ]
}
```

I've tried w/ both the `http-80` module as well as the `web` module for the source

**Comment by antonbabenko** [comment]
Something like this should work (taken from `examples/http`):

```
module "web_server_sg" {
  source = "terraform-aws-modules/security-group/aws//modules/http-80"

  name        = "web-server"
  vpc_id      = "${data.terraform_remote_state.vpc.us_east_vpc1_id}"

  ingress_cidr_blocks = ["0.0.0.0/0"]

  # Allow engress HTTP 80 rules to outside
  egress_rules = ["http-80-tcp"]
}
```

The examples are different depending on how `source` is specified. See `examples/complete` and `examples/http` for exact details.

**Comment by veilig2000** [comment]
I originally had a setup similiar to this.  I tried to go w/ the `ingress_with_cidr_blocks` route so I could set a description on the rule of what the IP is for.  If you just use the `ingress_cidr_blocks` option, are you able to set a description on the rule?  This is helpful in my organization.

**Comment by antonbabenko** [comment]
To have a possibility for more customization like you are describing you should use root of the module as source and then specify arguments like this:
```
source = "terraform-aws-modules/security-group/aws"

ingress_with_cidr_blocks = [
    {
      rule        = "postgresql-tcp"
      cidr_blocks = "0.0.0.0/0,2.2.2.2/32"
    },
    {
      rule        = "postgresql-tcp"
      cidr_blocks = "30.30.30.30/32"
    },
    {
      from_port   = 10
      to_port     = 20
      protocol    = 6
      description = "Service name"
      cidr_blocks = "10.10.0.0/20"
    },
  ]

```

**Comment by veilig2000** [comment]
that works great!  thanks for your help!

**Comment by antonbabenko** [comment]
Great! You are welcome.
