### ISSUE TITLE
Creation of group with IPv6 ICMP rules hangs and returns error

### ISSUE THREAD

**Issue by audiolomb** [terraform-aws-modules/terraform-aws-security-group#77]
To reproduce:

`module "Test-ICMP-V6" {
  source = "terraform-aws-modules/security-group/aws"

  name        = "Test-ICMP-V6"
  description = "this is a test"
  vpc_id      = "${data.aws_vpcs.vpc.ids[0]}"

  egress_with_cidr_blocks = [
    {
      from_port        = -1
      to_port          = -1
      protocol         = "58"
      description      = "ICMP V6 ALL"
      ipv6_cidr_blocks = ["::/0"]
    },
  ]
}`

Behavior:

The group gets created on AWS

![sg01](https://user-images.githubusercontent.com/43075373/46024515-d1601900-c09b-11e8-9a60-8880bc8338bc.png)

However,  terraform does not return success. After  minutes it times out with an error:

![sg02](https://user-images.githubusercontent.com/43075373/46024916-99a5a100-c09c-11e8-8167-154a3ed9e429.png)

Creating the group as an aws_security_group resource works fine.

Thank you.

**Comment by antonbabenko** [comment]
If you need IPv6 rules you should specify it like this:

```hcl
egress_with_ipv6_cidr_blocks = [
    {
      from_port        = 300
      to_port          = 400
      protocol         = "tcp"
      description      = "Service ports (ipv6)"
      ipv6_cidr_blocks = "2001:db8::/64"
    },
  ]
```

not using `egress_with_cidr_blocks`.

**Comment by audiolomb** [comment]
sorry, that was a bad cut and paste...

here is the code:

module "Test-ICMP-V6" {
  source = "terraform-aws-modules/security-group/aws"

  name        = "Test-ICMP-V6"
  description = "this is a test"
  vpc_id      = "${data.aws_vpcs.vpc.ids[0]}"

  egress_with_ipv6_cidr_blocks = [
    {
      from_port        = -1
      to_port          = -1
      protocol         = "58"
      description      = "ICMP V6 ALL"
      ipv6_cidr_blocks = "::/0"
    },
  ]
}


Note that I am using ICMP, not TCP.

The behavior is the same.

**Comment by antonbabenko** [comment]
There are some inconsistencies/bugs in the way how Terraform AWS provider handles AWS EC2 security group duplicates.

This code creates egress for IPv6:

```
  egress_with_ipv6_cidr_blocks = [
    {
      from_port = -1
      to_port = -1
      protocol = "icmpv6"
      description = "ICMP V6 ALL"
      ipv6_cidr_blocks = "::/0"
    },
  ]
```

This code creates the same for IPv4:

```
  egress_with_cidr_blocks = [
    {
      from_port = -1
      to_port = -1
      protocol = "icmpv6"
      description = "ICMP v6 ALL"
      cidr_blocks = "0.0.0.0/0"
    },
  ]
```

Hope ot helps.

**Comment by audiolomb** [comment]
Hi Anton,

Changing the code to this

```
module "Test-ICMP-V6" {
  source = "terraform-aws-modules/security-group/aws"

  name        = "Test-ICMP-V6"
  description = "this is a test"
  vpc_id      = "${data.aws_vpcs.vpc.ids[0]}"

  egress_with_ipv6_cidr_blocks = [
    {
      from_port        = -1
      to_port          = -1
      protocol         = "icmpv6"
      description      = "ICMP V6 ALL"
      ipv6_cidr_blocks = "::/0"
    },
  ]
}
```

unfortunately will not do what's needed. Here's what gets created on AWS:

![image](https://user-images.githubusercontent.com/43075373/46627337-0bdfa200-caef-11e8-96cc-816a7adc7ea1.png)

Which opens ALL protocols, not just ICMP.

Claudio

**Comment by audiolomb** [comment]
That works! Thank you!

Ignore the previous comment, if you ever received it! I was just to sleepy! :-)

**Comment by antonbabenko** [comment]
If I understand correctly AWS Console the type is "Custom ICMP Rule - IPV6" means what you need - ICMP. Protocol "All" means that everything of that type is open.
