### ISSUE TITLE
Value of 'count' cannot be computed

### ISSUE THREAD

**Issue by jdb1441** [terraform-aws-modules/terraform-aws-security-group#78]
Hello,

It appears that the changes made to the output file from commit "Make use of name_prefix optional (#74)" is causing errors when we try to run a plan with security groups referencing an ingress with source security group id. We receive the following error for each security group:

> * module._subnet_name_.aws_security_group_rule.ingress_with_source_security_group_id: aws_security_group_rule.ingress_with_source_security_group_id: value of 'count' cannot be computed

I have traced this back to the following change in the output file:
Original working code:
```
output "this_security_group_id" {
  description = "The ID of the security group"
  value       = "${element(concat(aws_security_group.this.*.id, list("")), 0)}"
}
```
Updated broken code:
```
output "this_security_group_id" {
  description = "The ID of the security group"
  value       = "${element(concat(coalescelist(aws_security_group.this.*.id, aws_security_group.this_name_prefix.*.id), list("")), 0)}"
}
```

We are running on tf version v0.11.2, but coalescelist was introduced in v0.9.4 so that shouldn't be a problem. Please let me know if there is any additional information you would like.

**Comment by antonbabenko** [comment]
You should specify `computed_ingress_with_source_security_group_id` instead of `ingress_with_source_security_group_id` argument and set `number_of_computed_ingress_with_source_security_group_id` when referencing computed values (values from the module).

See this example:
https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/3ce61607c2c83e73f482dc0cc4e2c51f48f83626/examples/computed/main.tf#L46-L53

Could you show the code how you invoke this module, I don't understand why `output` is not working for you.

**Comment by jdb1441** [comment]
Hi Anton,

Here is an example of how I am invoking it that works fine with the old version of the output and fails with the new:

```
module "example_sg" {
  source = "terraform-aws-modules/security-group/aws"

  name        = "${var.environment}-example"
  description = "Security group for example"
  vpc_id      = "${module.vpc.vpc_id}"

  ingress_with_cidr_blocks = [
    {
      from_port   = 22
      to_port     = 22
      protocol    = "tcp"
      description = "default ssh port"
      cidr_blocks = "1.2.3.4/32"
    },
  ]

  ingress_with_source_security_group_id = [
    {
      from_port                = 22
      to_port                  = 22
      protocol                 = "tcp"
      description              = "SSH"
      **source_security_group_id = "${module.other_example_sg.this_security_group_id}"**
    }
  ]

  egress_rules = ["all-all"]
}

```

**Comment by jdb1441** [comment]
Hey @antonbabenko ,

Any idea on why this is happening? This is causing significant problems so we will likely be moving to our own module with the previous code if we can't get this resolved soon.

Thanks!
Josh

**Comment by antonbabenko** [comment]
As I have pointed out in the previous comment, you need to specify configuration inside `computed_ingress_with_source_security_group_id` instead of `ingress_with_source_security_group_id` if you are using values from modules.

Also add `number_of_computed_ingress_with_source_security_group_id = 1`.

**Comment by antonbabenko** [comment]
Closing this issue.
