### ISSUE TITLE
"the specified rule <rule> already exists"

### ISSUE THREAD

**Issue by PeterGrace** [terraform-aws-modules/terraform-aws-security-group#82]
I have a terraform recipe where I create via interpolation a set of security groups to authorize ssh access to our instances.  When the list of addresses changes, it causes the interpolation to also change, such that all of the security_group_rules need to be deleted and recreated.  Unfortunately, the new rules are trying to create while the old rules are still deleting, and I get an error message like below:
```
* aws_security_group_rule.entries[38]: 1 error(s) occurred:

* aws_security_group_rule.entries.38: [WARN] A duplicate Security Group rule was found on (sg-db2b8396). This may be
a side effect of a now-fixed Terraform issue causing two security groups with
identical attributes but different source_security_group_ids to overwrite each
other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
information and instructions for recovery. Error message: the specified rule "peer: redacted/32, TCP, from port: 22, to port: 22, ALLOW" already exists
* aws_security_group_rule.entries[36]: 1 error(s) occurred:

* aws_security_group_rule.entries.36: [WARN] A duplicate Security Group rule was found on (sg-db2b8396). This may be
a side effect of a now-fixed Terraform issue causing two security groups with
identical attributes but different source_security_group_ids to overwrite each
other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
information and instructions for recovery. Error message: the specified rule "peer: redacted/32, TCP, from port: 22, to port: 22, ALLOW" already exists

Terraform does not automatically rollback in the face of errors.
```

Here's a snippet of how I generate the security group rules.  I set "create_before_destroy = false" on an expert's suggestion, however it has not solved the issue.  

```
resource "aws_security_group_rule" "entries" {
  count             = "${length(data.aws_security_groups.sg_list.ids) * length(var.authorized_ssh_rangelist)}"
  security_group_id = "${element(data.aws_security_groups.sg_list.ids, count.index / length(var.authorized_ssh_rangelist))}"
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  cidr_blocks       = ["${lookup(var.authorized_ssh_rangelist[count.index % length(var.authorized_ssh_rangelist)], "cidr")}"]
  description       = "${lookup(var.authorized_ssh_rangelist[count.index % length(var.authorized_ssh_rangelist)], "description")}"

  lifecycle {
    create_before_destroy = false
  }
}
```

**Comment by PeterGrace** [comment]
I'm not sure if this is the right project for this issue so I cross-posted to https://github.com/terraform-providers/terraform-provider-aws.

**Comment by antonbabenko** [comment]
Closing this issue here, because it does not belong to this module and @tomelliff has answered [here](https://github.com/terraform-providers/terraform-provider-aws/issues/6276#issuecomment-433460369).

I would just recommend to write more repetetive code and not try to emulate loops as you expect in general-purpose programming language. If you need to work with lists in Terraform (especially, statefull lists of AWS IAM Access Keys, which will be new every time you recreate them, for example), you can use [jsonnet](https://github.com/google/jsonnet).

Minor thing is that `count.index % length(var.authorized_ssh_rangelist)` can be simplified to `count.index`.
