### ISSUE TITLE
Group name value.

### ISSUE THREAD

**Issue by jarrettj** [terraform-aws-modules/terraform-aws-security-group#86]
Hi,

Good day.

Is there any reason why the "Group Name" has this long generated number at the back? Example:
```
example20181022054634731400000003
```

Is there a valid need for that? Thanks.

Regards.
JJ

**Comment by DamaniN** [comment]
Noticed the same thing, looking for an answer myself.

**Comment by antonbabenko** [comment]
Security groups can be created with the fixed name `use_name_prefix = false` or with specified `name` as a prefix (`use_name_prefix = true`).

By default, `use_name_prefix = true` which means that security group will be possible to update if it has dependencies (it will create a new security group and delete the previous one).

The only downside of `use_name_prefix = true` is that it appends date+numbers as you noted.

Let me know if you have other questions.
