### ISSUE TITLE
use_name_prefix causes error

### ISSUE THREAD

**Issue by kaneboojer** [terraform-aws-modules/terraform-aws-security-group#92]
module.sg.output.this_security_group_id: cannot parse "${var.create && var.use_name_prefix ? 1 : 0}" as an integer

Terraform code:
module "ssh_sg" {
  source = "terraform-aws-modules/security-group/aws"
  name        = "ssh-${var.environment}"
  description = "Default security group"
  vpc_id      = "${data.terraform_remote_state.global_state.vpc_id}"
  ingress_rules = ["ssh-tcp"]
  ingress_cidr_blocks      = ["0.0.0.0/0"]
  tags = "${var.global_tags}"
}

I suspect either 
https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/main.tf#L12
or 
https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/main.tf#L25
is causing this. Has been an issue for me since vers 2.4 so I've just been using that.

**Comment by puzzloholic** [comment]
I currently upgrade from 2.3.0 to 2.9.0 with submodule http-80, postgresql, and redis. In those module there is no way to set use_name_prefix, so it will be defaulted to true, and change of name will force a new resource. I want existing security group as is, no name prefix changing.

I assume all submodules still cannot modify use_name_prefix.

Please make it modifiable from any submodules

**Comment by antonbabenko** [comment]
[v2.10.0](https://github.com/terraform-aws-modules/terraform-aws-security-group/releases/v2.10.0) has been released.

@kaneboojer Could you please try the latest release and comment if the problem persists.
