### ISSUE TITLE
prefix_list rule

### ISSUE THREAD

**Issue by mrg2k8** [terraform-aws-modules/terraform-aws-security-group#96]
Hello,

I really like this module and have bumped into a corner case. In the current form, is it possible to create a rule inside the module and apply it to a prefix list? For example, something along these lines:

```
module "some-sg" {
  source = "../modules/terraform-aws-security-group"

  vpc_id = "${module.somevpc.vpc_id}"

  name        = "some-sg"

computed_egress_with_source_security_group_id = [
    {
      rule                     = "postgresql-tcp"
      source_security_group_id = "${module.someother-sg.this_security_group_id}"
    },
    {
      rule                     = "https-443-tcp"
      prefix_list_ids = ["${module.somevpc.vpc_endpoint_s3_pl_id}"]
     description              = "HTTPS 443 towards S3 VPC endpoint"
    }
  ]

  number_of_computed_egress_with_source_security_group_id = 2
}
```

Of course, the snippet above does not work, because the second rule is missing the `source_security_group_id` parameter.

The end result is that I want to have a HTTPS (TCP 443) rule only towards the VPC endpoint, not towards the other destinations declared on the security group module. The `egress_prefix_list_ids` option creates a rule for all the destinations, which is not the behavior I need.

Do I have to modify the module to achieve this or is there a way to do it with the current implementation?

Thanks.

**Comment by mrg2k8** [comment]
As a workaround (without modifying the module), I've used the vpc_endpoint data source (https://www.terraform.io/docs/providers/aws/d/vpc_endpoint.html#prefix_list_id) and a separate security group.

**Comment by Dogers** [comment]
@mrg2k8 have you got an example of what you've done? Just hit this same issue :(

**Comment by mrg2k8** [comment]
Hello, sorry for the late reply (I was away). Here's a snippet that achieves what I wanted, with the downside of having a separate SG:
```
module "pl-test-sg" {
  source = "../../modules/terraform-aws-security-group"

  vpc_id = "${module.somevpc.vpc_id}"

  name        = "pl-test-sg"
  description = "pl-test-sg"

  egress_ipv6_cidr_blocks = []
  egress_cidr_blocks = []

  egress_rules = ["http-80-tcp", "https-443-tcp"]

  egress_prefix_list_ids = ["${module.somevpc.vpc_endpoint_s3_pl_id}"]
```
