### ISSUE TITLE
source_security_group_id always detect changes when referencing SG in another account using vpc peering

### ISSUE THREAD

**Issue by mabitt** [terraform-aws-modules/terraform-aws-security-group#97]
Hi, I'm referencing a security group in another account/vpc linked using vpc peering, and every time I execute `terraform plan` for any unrelated change, it lists this change:

```
Terraform will perform the following actions:

-/+ module.sg_servers_rds.aws_security_group_rule.ingress_with_source_security_group_id (new resource required)
      id:                       "sgrule-1234567890" => <computed> (forces new resource)
      description:              "MySQL - remote servers" => "MySQL - remote servers"
      from_port:                "3306" => "3306"
      protocol:                 "tcp" => "tcp"
      security_group_id:        "sg-12345678901234567" => "sg-12345678901234567"
      self:                     "false" => "false"
      source_security_group_id: "sg-12345678" => "123456789012/sg-12345678" (forces new resource)
      to_port:                  "3306" => "3306"
      type:                     "ingress" => "ingress"

Plan: 1 to add, 0 to change, 1 to destroy.
```

My terraform code is:

```
module "sg_servers_rds" {
  source      = "terraform-aws-modules/security-group/aws"
  version     = "2.10.0"

  name        = "SG-SERVERS-RDS"
  description = "Security group for RDS Access"
  vpc_id      = "${nice.vpc.id}"

  egress_rules        = ["all-all"]
  ingress_with_source_security_group_id = [
    {
      rule        = "mysql-tcp"
      description = "MySQL - remote servers"
      source_security_group_id = "123456789012/sg-12345678"
    },
  ]
}

```

Is that a bug or I'm doing something wrong?

Thanks.

**Comment by antonbabenko** [comment]
Thanks for opening this issue!

The problem is related to the way how ID can be referenced between VPCs.

It is a part of a pretty complex improvement, which is related to many networking resources in AWS. I will try to dedicate some time to work on it in during next 2-3 weeks, but can't promise an exact time for the fix.

**Comment by pydo** [comment]
I ran into this bug last week when referencing a security group from a `remote_state_file`.
Anytime I run a `plan` that references the remote security group, Terraform thinks that it needs to be deleted and re-created.

This is a pretty critical bug IMO since it causes all plans to fail when the security group is being used.
I'll edit this comment with some code the reproduces the issue later.

**Comment by e-moshaya** [comment]
same issue here

**Comment by Tensho** [comment]
Have the same issue

**Comment by jayolmos** [comment]
same issue

**Comment by aly-saleh-a** [comment]
same issue

**Comment by pauloresendejr** [comment]
Same issue

**Comment by yoadfe** [comment]
same issue

**Comment by pauloresendejr** [comment]
I fix the problem , put only sg group id.

using the example 

module "sg_servers_rds" {
  source      = "terraform-aws-modules/security-group/aws"
  version     = "2.10.0"

  name        = "SG-SERVERS-RDS"
  description = "Security group for RDS Access"
  vpc_id      = "${nice.vpc.id}"

  egress_rules        = ["all-all"]
  ingress_with_source_security_group_id = [
    {
      rule        = "mysql-tcp"
      description = "MySQL - remote servers"
      source_security_group_id = **"123456789012/sg-12345678"**
    },
  ]
}


module "sg_servers_rds" {
  source      = "terraform-aws-modules/security-group/aws"
  version     = "2.10.0"

  name        = "SG-SERVERS-RDS"
  description = "Security group for RDS Access"
  vpc_id      = "${nice.vpc.id}"

  egress_rules        = ["all-all"]
  ingress_with_source_security_group_id = [
    {
      rule        = "mysql-tcp"
      description = "MySQL - remote servers"
      source_security_group_id = **"sg-12345678"**
    },
  ]
}
